### ISSUE TITLE
Encoding always escapes as if JSON may be embedded in HTML

### ISSUE THREAD

**Issue by timbod7** [bos/aeson#111]
It seem that json strings are always being encoded as if they might need to be embedded in HTML.

See the following ghci output:

Prelude> Data.Aeson.Encode.fromValue (Data.Aeson.String (Data.Text.pack "a<b>")) 
"\"a\u003cb\u003e\""
Prelude> 

I have JSON data with _many_ '<' and '>" chars, and it's verbose and ugly to have them all encoded like this. This was apparently introduced in issue #81  to prevent  issues when embedding in HTML. My data will never be embedded in HTML, and I don't think the JSON standard requires this encoding.

Is it really the job of the fromValue method to avoid XSS attacks? I would have thought that was the job of the code that actually embeds the some JSON in some HTML.

**Comment by hawkish** [comment]
I actually have to un-escape the json again to use it in iOS applications. So I would tend to agree with timbod7 on this: It should be the responsibility of the embedder to make sure that things are properly escaped.

**Comment by phadej** [comment]
FWIW, `aeson` produces correct JSON, one could escape every character inside strings, and it's still correct JSON. So I strongly advice on not relying on whether content of strings is escaped or not.

i.e. JSON standard doesn't require the encoding of `<` and `>`, but it doesn't forbid it either.

I'm :-1: on changing this back and forth, shouldn't really matter in proper consumers.

**Comment by hawkish** [comment]
Maybe you should consider making the escaping optional - maybe as parameter. Let the users decide for themselves how they want their JSON encoding.

**Comment by tolysz** [comment]
https://tools.ietf.org/html/rfc7159#page-8 

    All Unicode characters may be placed within the
    quotation marks, except for the characters that must be escaped:
    quotation mark, reverse solidus, and the control characters (U+0000
    through U+001F).

    Any character may be escaped.  If the character is in the Basic
    Multilingual Plane (U+0000 through U+FFFF)

I think the decoding of `\uXXXX`'s should be done transparently to the user... as you could escape all characters and have exactly the same string.

**Comment by hawkish** [comment]
The entire quote is: The representation of strings is similar to conventions used in the C
   family of programming languages.  A string begins and ends with
   quotation marks.  All Unicode characters may be placed within the
   quotation marks, except for the characters that must be escaped:
   quotation mark, reverse solidus, and the control characters (U+0000
   through U+001F).
So the quotation at the beginning and at the end shouldn't be escaped.

**Comment by tolysz** [comment]
> quotation at the beginning and at the end shouldn't be escaped.

There are no quotations :) inside _container_'s quotations 

    Data.ByteString.Lazy.putStr $ Data.Aeson.encode  (Data.Aeson.String (Data.Text.pack "a<b>")) 

It is artefact of `show`

**Comment by hawkish** [comment]
I had a closer look at my haskell code. Bad show. Bad show. My bad. Sorry.
