### ISSUE TITLE
request for comment: instances for Network.URI.URI?

### ISSUE THREAD

**Issue by frasertweedale** [bos/aeson#165]
I'm currently newtype'ing Network.URI.URI to provide (non-orphan) FromJSON and ToJSON instances for URIs.

Considering network is included in the Haskell Platform, would you have any objections to including instances for URI in aeson @bos?  If not, I will happily submit the pull request.

**Comment by MaxDaten** [comment]
URI is still present in package `network-uri` and still widely used. Is there still any reason to omit `FromJSON`/`ToJSON`?

**Comment by MaxGabriel** [comment]
For anyone looking for this, there is https://hackage.haskell.org/package/network-uri-json
