### ISSUE TITLE
Consider adding back escaping of '<' and '>' to prevent XSS injection

### ISSUE THREAD

**Issue by meiersi** [bos/aeson#180]
I've just noticed that aeson-6.2.1 also escaped '<' and '>' characters (see for example https://github.com/bos/aeson/blob/6bae92494c1aeae4befdf2a87e5d9cd026b40e8b/Data/Aeson/Encode.hs#L79).

The new encoder does not do that. @bos, should I re-add the behaviour? When exactly is this escaping preventing an XSS injection? Note that in terms of encoding size this escaping is quite costly  when embedding HTML documents in JS strings. So, I'd like to understand why it is needed. I also suspect that it would be sufficient to only escape '<', as then it would be impossible to start a tag.

**Comment by avieth** [comment]
+1 for *not* escaping these, because there are applications which demand human-readable JSON. For instance, programmatically building or altering a node.js package.json file. It's not a huge cost: the package.json file will be interpreted correctly even with the `<, >` characters escaped, but it will be *slightly-less* readable.

**Comment by lpsmith** [comment]
Well, you can't build a correct json-in-html escaping function from a correct json escaping function and a correct html escaping function.   So while I agree that escaping angle brackets is undesirable in some cases,   it's also necessary in a very common use case.

I don't really have an complete answer on this count.    It's kind of an ugly problem that's arisen from the lack of syntax engineering that went into embedded JavaScript.

**Comment by snoyberg** [comment]
I was unaware of this change, and it's subtly introduced a potential for XSS attacks in Yesod. See this thread:

https://groups.google.com/d/msg/yesodweb/M2VS5OTwyPg/AnN5nAm1AgAJ

Note that this is _not_ about embedding unsanitized data in an innerHTML. This can be triggered by a perfectly safe usage of sanitized data being embedded inside an innerText. The problem comes from a string like:

    "</script><script>alert('hacked!')</script>"

Before this change, the less than signs would be escaped, meaning this was safe to embed inside a `<script>` tag, and the resulting string could be used for `innerText`. That's no longer the case.

**Comment by mbj** [comment]
JSON encodes opaque generic strings that are represented in UTF-8. A JSON encoder should use the most efficient representation, only triggering escapes when technically required. This follows the rule of least power, a decent engineering axiom.

Many data formats, including HTML can be encoded into that generic JSON strings, even JSON itself. Hence this library nor any other JSON encoder should consider to add format specific special cases.

In case of the proposed special case it would even be very misleading, there are many instances of XSS vectors that do not even require the ability to inject `<` and `>` characters. A JSON encoder cannot be aware of all of these, nor can escaping stop them.

Whats next, triggering unicode escapes for characters in SQL keywords? Parse strings against all known languages on encode and query an IDS on the tokens?

I propose to close this issue, and advice everyone who thinks the proposed special case is a good idea to guard strings for interpolation into HTML (or any other string based language) to learn about type save interpolation, or constructing ASTs of the target language (from data that may went through JSON) with decent language specific escapes on unparsing.

**Comment by bergmark** [comment]
Well put!

**Comment by lpsmith** [comment]
I disagree that this is best handled similarly to #389,  as stripping the BOM is a problem trivially solved by function composition.   This problem requires a rather different solution;  though I agree the default should not be to escape `<` and `>`,  at the same time you basically have to start over from stratch with an encoder if you want to properly support JSON-in-HTML.   While a JSON encoder is a fairly simple bit of code,  it's still more than a couple of lines.

**Comment by mbj** [comment]
@lpsmith What prevents you from encoding JSON into HTML via the same functionality you'd encode any untrusted string into HTML?

**Comment by lpsmith** [comment]
@mbj try this:

~~~
<html>
<body>
<script>
  var foo = "&lt;Hello!&gt;"
  alert(foo)
</script>
<p>&lt;Hello!&gt;</p>
</body>
</html>
~~~

May I suggest having `encode`,  `encodeForHTML`,  and perhaps `encodeWithExtraEscapes :: (Char -> Bool) -> ...`

**Comment by lpsmith** [comment]
@mbj 

> You need a script/js specific encoder to be use on interpolation of your string

What,  like `encodeForHTML`?   That's what I've been saying all along.

**Comment by mbj** [comment]
@lpsmith I mean a generic encoder for a generic UTF-8 string to be used in an HTML script tag. Effectively you are interpolating untrusted strings into the script tag, that needs to be solved at the HTML builder side.

I meant the HTML encoder, not the JSON encoder.

**Comment by mbj** [comment]
Bonus points: If you solve it at the HTML builder side: You can interpolate ANY string correctly, not only the ones that come from a "tuned" JSON encoder.

**Comment by lpsmith** [comment]
I strongly disagree.   Solving it at the HTML encoder side means you have to understand the syntax of JavaScript.    Offering it as an option here means you just have to escape a couple of extra characters in JSON.

**Comment by mbj** [comment]
@lpsmith So you create an interface that interpolates any string into HTML under the premise it was encoded with a "magical" JSON encoder? What prevents you from screwing up later iterations and place a string into the interpolation that not went through the JSON encoder? Not the type checker.

But if you'd like to have a magic JSON encoder, as long its not the default in aeson I'm not in your way.

**Comment by neongreen** [comment]
@mbj Well, on the other hand you have to realise that simple string templating is pretty convenient. If the choice is between “use string templating, possibly unsafe” and “use a full-blown Javascript generation library”, I'd probably use the former (and then I'd be lobbying for changes like this in Aeson, yeah, right).

**Comment by bergmark** [comment]
Is there a reason to not include the script using the `src` attribute instead?

**Comment by neongreen** [comment]
@bergmark: I use Javascript for design “niceties” (hiding some fields when the value of `<select>` changes, etc) and it's *really* inconvenient to have this logic decoupled from actual HTML (which I have to do right now for unrelated reasons). If I could inline my Javascript instead of having to use `src`, I would.

(Once again, I'm not actually saying that we should have this change made in Aeson, I'm just saying that there are reasons why others would want that, such as “when your Javascript is unchecked anyway, at least you can optimise for convenience and especially for avoidance-of-nasty-surprises”.)

**Comment by lpsmith** [comment]
> (and then I'd be lobbying for changes like this in Aeson, yeah, right)

Offering `encodeForHTML` has the ancillary benefit of raising awareness of this particular issue.   And you can ignore it if you've got a better solution.   I agree that we should leave `encode` as-is, with minimal escaping.

**Comment by mbj** [comment]
> I agree that we should leave encode as-is, with minimal escaping.

Thats the only thing I'm looking for. And I'd even lobby against HTML unchecked interpolation ready optional encode API, because I as a library author would dislike to provide something that inherity unsafe. But I'm not the library author, and as I reached my goal "strict `encode`", I'm happy ;)
