### ISSUE TITLE
Add decode function accepting all JSON values

### ISSUE THREAD

**Issue by hesselink** [bos/aeson#194]
Would you be interested in a top-level decoding function that accepts all JSON values instead of just arrays and objects? I know this violates the RFC, but there are many situations where this would be useful, and the implementation is actually pretty long (with all the extra attoparsec imports etc). Also, `encode` and related functions currently produce values that `decode` cannot parse.

We have these implemented in a utils package, so if you want, I can easily send a pull request.

**Comment by neongreen** [comment]
> Why not just change decode to comply with the latest RFC and bump the version number of Aeson accordingly?

This has been done, apparently.

Can the issue be closed?
