### ISSUE TITLE
constructorTagModifier doesn't get applied

### ISSUE THREAD

**Issue by k-bx** [bos/aeson#195]
I just tried something similar to example from doc on Aeson.TH and it seems constructorTagModifier doesn't get applied.

``` haskell
{-# LANGUAGE TemplateHaskell #-}

module HaskCheck where

import           Data.Aeson.TH (Options (..), defaultOptions, deriveJSON)

import           Data.Char     (toLower)

data User = User { userName :: String
                 , userPass :: String
                 } deriving Eq

$(deriveJSON defaultOptions { fieldLabelModifier = drop 4
                            , constructorTagModifier = map toLower }
  ''User)


-- λ> encode (User "foo" "bar")
-- "{\"Name\":\"foo\",\"Pass\":\"bar\"}"
```

**Comment by jberryman** [comment]
So is this not an issue? Something more than a "sorry, stupid me" would have been very helpful to very tired me.

**Comment by k-bx** [comment]
@jberryman "constructor tag modifier" means something that works on algebraic datatypes, e.g. if you'd serialize type `data Foo = Foo | Bar | Baz`, and not what I initially thought in this issue. Is that helpful?
