### ISSUE TITLE
Add generic encoding option to reject unknown field-names

### ISSUE THREAD

**Issue by hvr** [bos/aeson#207]
I've started converting my previously hand-written instances in terms of `genericParseJSON` and `genericToJSON`, but one thing I'm missing though is to
have `genericParseJSON` (optionally) result in a parser error, if an unexpected/unknown field occurs in the JSON object. 

For me, this is quite useful in (some) cases (especially when `Maybe`-fields are involved) when implementing JSON services to notice clients which have sent data with mistyped field-names, as well as on the client-side, to notice new/unhandled field-labels returned by a service (or when I mistyped the field-name in the client-code).

/cc @basvandijk

**Comment by sol** [comment]
I need this too.  I think the current behavior is good as a default, but having a way to configure this through `Data.Aeson.Types.Options` would be nice.

**Comment by rmanne** [comment]
@basvandijk would you be OK with an implementation that focuses on TH first and only later add Generics support? I'm having trouble finding a good way to do it with generics.

Consider data types:
```
data X = X
data A = A { a :: X }
data B
    = B1 { b1 :: X }
    | B2 { b2 :: X }
```

A is fairly trivial. We can simply say, if the object contains any keys aside from "a", fail. B is more complex, and I think there's a related TODO [here](https://github.com/rmanne/aeson/blob/master/Data/Aeson/TH.hs#L415). `tagFieldName opts` should be a valid tag, so we have to accept it as part of the object, but we shouldn't accept it if it's not a sum. In this example, I would expect:

```
{"tag": "A", "a": "X"} -> Error ("Unknown fields: [\"tag\"]")
{"tag": "B1", "b1": "X"} -> Success (B1 { b1 = X })
```

The way the classes are defined in FromJSON doesn't offer a lot of this context that I think would be very nice to have, so attempting to have the new option support generics would require more substantial changes.

**Comment by bergmark** [comment]
This is resolved.
