### ISSUE TITLE
Allow integer and fixed point notation when writing values to json.

### ISSUE THREAD

**Issue by trilogysci** [bos/aeson#227]
All numbers are converted to scientific notation which is not standard representation in most browsers and does not support fixed point notation required by currency. Currently anything below 0.1 and 1000000 or above is converted to scientific notation. Also, all integer values are converted to floating point.
toJSON (0.01 ::Centi) results in "Number 1.0e-2"
toJSON (1 ::Int) results in "Number 1.0"
toJSON (10000000 ::Int) results in "Number 1.0000000e7"

**Comment by bergmark** [comment]
interestingly this is not the case when using `encode` on `Int`

```haskell
λ> let x = (10000000 ::Int) in (encode x, toJSON x)
("10000000",Number 1.0e7)
λ> let x = (1 ::Int) in (encode x, toJSON x)
("1",Number 1.0)
λ> let x = (0.01 :: Centi) in (encode x, toJSON x)
("1.0e-2",Number 1.0e-2)
```

**Comment by phadej** [comment]
Is this issue opened pre-`toEncoding`? With `toEncoding` it's easy to control how stuff is encoded. So this is kind-of non-issue already, similar to ordering the keys in a map.

**Comment by mindreader** [comment]
If I might ask, how do you solve this with toEncoding?  I cannot see any way print a Value with large integers in it to any string that uses fixed point notation without writing my own encoder from the ground up.

**Comment by phadej** [comment]
@mindreader: `newtype`

**Comment by mindreader** [comment]
This is as close as I can get to that solution.

    newtype ValueFixed = ValueFixed Value deriving Generic
                        
    encodeFixed :: Value -> Encoding
    encodeFixed (Number n) = toEncoding $ formatScientific Fixed Nothing n
    encodeFixed (Array a) = mconcat $ V.toList $ fmap encodeFixed a
    encodeFixed (Object o) = undefined  -- I can't figure out how to make a series from this.
    encodeFixed v = toEncoding v  

    instance ToJSON ValueFixed where
      toEncoding (ValueFixed v) = encodeFixed v

**Comment by phadej** [comment]
@mindreader why you don't have a newtype wrapper around a field you want to encode:
```hs
newtype MyInteger = MyInteger Integer

instance ToJSON MyInteger where
    toEncoding (MyInteger i) = ...
```
?

**Comment by mindreader** [comment]
My use case is that I have created a large Value from an epically long json string, tweaked it slightly, and now I want to turn it back into a string.  The original json had no scientific notation but now some numbers are displayed in scientific notation because they merely happened to fall into a certain range.

Javascript and most libraries deal with it, but I'm afraid of incompatibilities down the line with poorly written decoders and client side libraries, and I'd rather just have the numbers be fixed point from the start.

**Comment by phadej** [comment]
The main purpose of `aeson` to my understanding, is to provide serialisation/deserialisation to/from JSON format. The editing of `Value`, especially in "formatting preserving" way is out-of-scope.

I'd suggest, to parse data into a data type (special made, not `Value`), tweak it, and encode it back.
That's not an easy way, but IMHO *righter.

Also, hopefully, there are less and less poorly written JSON libraries out there, as JSON is used everywhere, and isn't even complicated. You are probably afraid for no reason.

**Comment by mindreader** [comment]
I ended up writing this.  Not sure if I saved myself any work.

    newtype ValueFixed = ValueFixed Value deriving Generic

    instance ToJSON ValueFixed where
      toEncoding (ValueFixed v) = encodeFixed v

    encodeFixed :: Value -> Encoding
    encodeFixed (Number n) = unsafeToEncoding $ BS.string8 $ formatScientific Fixed Nothing n
    encodeFixed (Array a) = mconcat $ intersperse (unsafeToEncoding ",") $ V.toList $ fmap encodeFixed a
    encodeFixed (Object o) =
      unsafeToEncoding ("{") <>
        (mconcat . intersperse (unsafeToEncoding ",") .  fmap objEnc . reverse . HM.toList) o <>
        unsafeToEncoding ("}")
      where
        objEnc :: (T.Text, Value) -> Encoding
        objEnc (k, v)= toEncoding k <> unsafeToEncoding ":" <> encodeFixed v
    encodeFixed v = toEncoding v

It would be nice if there were an encodeWithOptions function which took an Options type although I can't think of any other options I'd support.

**Comment by seagreen** [comment]
@basvandijk: Note that so little is required of a valid JSON parser or generator that being spec conforming isn't very meaningful. I learned this [on Reddit of all places](https://www.reddit.com/r/programming/comments/59htn7/parsing_json_is_a_minefield/d98qxtj/). For example, `Value`'s `Number` constructor could take no arguments at all, we could convert all JSON numbers to just plain `Number`, we could serialize `Number` as `123`, and we would still be perfectly compliant.

**Comment by mindreader** [comment]
in hindsight, my fears of a non compliant encoders/decoders was somewhat misplaced.  It could still happen but I have a feeling I'm unlikely to run into one.

What `aeson` is doing is perfectly fine, it can generate json however it wants to.  Supporting a slightly different way to render output would be nice, but honestly I'm not sure if it is worth the effort.

**Comment by bergmark** [comment]
Sound like we can close this then, feel free to re-open if you'd like!
