### ISSUE TITLE
deriveJSON and custom parsers

### ISSUE THREAD

**Issue by rbtcollins** [bos/aeson#235]
I wanted to use deriveJSON but ran into issue #197. I can't seem to see any way to teach deriveJSON how to use the custom parser presented in that issue. Clearly I can manually create it, which I will, but it seems like a useful feature would be a way to tell deriveJSON about some overrides.

**Comment by rbtcollins** [comment]
So, digging it looks like this is totally doable using newtype, but a little bit of docs would go a long way here. Beyond that I found that using Data.Time.ZonedTime Just Worked (tm) :)

**Comment by bos** [comment]
Not really clear what you were trying to do here, so it's hard to tell what documentation could be improved.

**Comment by rbtcollins** [comment]
I forget :/. I can dig up my code before I try the fix for 197. https://github.com/rbtcollins/scratchpad/blob/master/BugTask.hs was the thing I ended up using.
