### ISSUE TITLE
omitEmptyLists support for defaultOptions

### ISSUE THREAD

**Issue by robertmassaioli** [bos/aeson#236]
It would be great if emptyLists could be omitted from the serialised result and if a missing field was parsed into an empty list. That way we could just write:

    someField :: [a]

Instead of:

    someField :: Maybe [a]

And using omitNothingFields.

**Comment by bos** [comment]
I'm not going to add this, sorry. I've now gotten a few requests of the form "please add an option to omit empty containers of type `a`", which obviously leads to a complete mess.

If you can think of a way to generalise this idea beyond lists and `Maybe`, we might have something to talk about, but I'm not adding further special-case options.

**Comment by robertmassaioli** [comment]
That's fine with me. Atleast I now know that we will never support this and that Maybe [a] is the right way to do it. Thanks for hearing out the request. Cheers!
