### ISSUE TITLE
Deep merge

### ISSUE THREAD

**Issue by andrewthad** [bos/aeson#245]
It would be nice to have these functions available in `aeson`:
                               
    import qualified Data.Text.Lazy.Builder as Builder                                                
    import qualified Data.Text.Lazy as LText                                                          
    import Data.Aeson.Encode.Pretty                                                                   
    import Data.Aeson                                                                                 
    import Data.HashMap.Strict as HashMap                                                             
    import Control.Applicative                                                                        
    import Data.Traversable                                                                           
    import Control.Monad (join)                                                                       
                                                                                                      
    mergeValueNoOverlaps :: Value -> Value -> Maybe Value                                             
    mergeValueNoOverlaps = go                                                                         
      where                                                                                           
      go Null v = Just v                                                                              
      go v Null = Just v                                                                              
      go (Object a) (Object b) = fmap Object $ sequence $ HashMap.unionWith (\x y -> join $ liftA2 go x y) (fmap Just a) (fmap Just b)                                                                       
      go (Array a) (Array b) = Just $ Array $ a <> b                                                  
      go _ _ = Nothing                                                                                
                                                                                                      
    mergeValueLeftBiased :: Value -> Value -> Value                                                   
    mergeValueLeftBiased = go                                                                         
      where                                                                                           
      go Null v = v                                                                                   
      go (Object a) (Object b) = Object $ HashMap.unionWith go a b                                    
      go (Array a) (Array b) = Array $ a <> b                                                         
      go v _ = v   

These are occassionally useful for me, and I think that they would benefit others as well (although probably with some better names).

**Comment by mf59816** [comment]
+1.

I also like the names.  Only, perhaps `mergeValues...`  (plural)?

**Comment by andrewthad** [comment]
pluralizing them would probably be better

**Comment by imz** [comment]
I'd rather have the compiler check that the `Value` is of the wanted type than have the strange default cases. (I have also needed to modify/merge JSON objects produced by toJSON.)


I believe that whenever you use susch a function you really don't want to get a `Nothing` as the result because you believe that you have a JSON object (or a JSON array).

You are hiding the possible type mismatches from the compiler.

I have been thinking about reflecting the type of a JSON value in the type `Value` as a parameter (in GADT-style).

**Comment by bos** [comment]
I'm not going to add this, sorry. The behaviour is too messy and weird – it makes no sense to merge an array and an object, for instance.
