### ISSUE TITLE
omitNothingFields with Data.Strict.Maybe

### ISSUE THREAD

**Issue by k-bx** [bos/aeson#251]
I have a big bunch of data structures which have Generic-generated ToJSON/FromJSON instances. I am trying to convert all the `Maybe`-fields into `Data.Strict.Maybe`-fields, but the problem is that I use `omitNothingFields=True` option (to keep wire-data small, since most fields are `Nothing`s), but now I am loosing the `omitNothingFields` functionality, since it's hardcoded only for a default, lazy `Prelude.Maybe` type.

I'm not sure on the best solution, please help.

**Comment by bos** [comment]
There really isn't a best solution right now. I don't want to add a dependency on the `strict` package, and that would in any case bulk up the implementation quite a bit. I believe your best bet is to use a regular `Maybe` and evaluate its argument strictly at construction time of whatever its containing type is.

**Comment by k-bx** [comment]
Ok thanks.
