### ISSUE TITLE
`FromJSON`/`ToJSON` instances for `Day`

### ISSUE THREAD

**Issue by andrewthad** [bos/aeson#252]
I noticed that there are instances for `UTCTime` (and there's also the wrapper for the .NET serialization), but there are no instances for day. I think that it could be almost the same as the `UTCTime` instance:

    instance FromJSON Day where
        parseJSON = withText "Day" $ \t ->
            case parseTime defaultTimeLocale "%F" (unpack t) of
              Just d -> pure d
              _      -> fail "could not parse ISO-8601 date" -- maybe consider rewording for Day instance
    instance ToJSON Day where
        toJSON t = String $ pack $ formatTime defaultTimeLocale format t
          where
            format = "%F"

This won't cause aeson to pick up additional dependencies, and it will help those of us who use `Generic` or other typeclass tricks for getting instances for compositions of types.

**Comment by alexkyllo** [comment]
+1, this would be nice to have so that I don't have to implement an orphan instance in the Yesod app I'm building.

**Comment by andrewthad** [comment]
I can make a PR for this if I could get any assurances about it being accepted.

**Comment by bos** [comment]
Looks reasonable. You wouldn't need a separate `format` local variable here, though.
