### ISSUE TITLE
Generics are faster than TH?

### ISSUE THREAD

**Issue by neongreen** [bos/aeson#257]
I ran `benchmarks/AesonCompareAutoInstances` (compiled with GHC 7.8.4, `-O2`) and was surprised to see this:

~~~
benchmarking D/fromJSON/th
time                 8.280 μs   (8.219 μs .. 8.352 μs)
benchmarking D/fromJSON/generic
time                 3.336 μs   (3.200 μs .. 3.518 μs)
~~~

Is it the benchmark that is outdated? After all, it wasn't even compilable when I looked at it. Or is it GHC's fault, or something else? At any rate, `D` looks more like an average datatype than e.g. `BigSum` to me, so if generics are more than twice as fast in this case, perhaps the 

> Data.Aeson.TH provides template-haskell functions which will derive an instance at compile-time. The generated instance is optimized for your type so will probably be more efficient than [...]

line in Aeson's documentation is misleading.

(The compilable version of the benchmark is [here](http://lpaste.net/133428). I only added `return []` in 3 places to work around a TH limitation, and got rid of `bcompare`.)

**Comment by basvandijk** [comment]
Yes I remember this result when I wrote the generic decoders and was very surprised by it. At the time I didn't have much time to investigate it and attributed it to a faulty/non-representative benchmark. 

Though, it might be interesting to look at the TH generated code and the GHC Core output of both decoders and see if we can spot an inefficiency in the TH decoder.

@neongreen interested in doing that?

**Comment by neongreen** [comment]
@basvandijk I've investigated a bit now and it turned out that it was simply a faulty benchmark.

~~~ haskell
  [ let v = toJSON d
    in (d, d', v) `deepseq`
       bgroup "D"
       [ group "toJSON"   (nf   toJSON d)
                          (nf G.toJSON d)
                          (nf   toJSON d')
       , group "fromJSON" (nf (  fromJSON :: FJ T ) v)
                          (nf (G.fromJSON :: FJ T ) v)
                          (nf (  fromJSON :: FJ T') v)
       ]
~~~

Due to apostrophes in fields' names, the encoding of `d` is not identical to the encoding of `d'` – and when `nf (  fromJSON :: FJ T') v` attempts to parse `v` into `T'`, it fails with decoding error (which obviously takes less time than parsing the full thing). When I changed the code to use `v` and `v'`, TH `fromJSON` became twice as generic `fromJSON`.

**Comment by basvandijk** [comment]
Ah that makes sense. Thanks for investigating!
