### ISSUE TITLE
Wrong Generic ToJSON instance in GHCJS

### ISSUE THREAD

**Issue by k0001** [bos/aeson#258]
In GHCJS 7.10.1 (version https://github.com/ghcjs/ghcjs/commit/15b7a34ddc11075a335e097f6109ad57ca03edab, installed from Nix as of https://github.com/nixos/nixpkgs/commit/f0311f9b8cd142a83ffcf738138fa51d0064e115), `ToJSON` instances that are derived using `Generic` are wrong.

I wrote the following snippet of code and ran it using both GHC 7.10.1 and GHCJS 7.10.1. You can see that even while the `Generic` representation in both compilers is the same, the `ToJSON` instance derived from `Generic` in GHCJS doesn't work as expected:

```haskell
{-# LANGUAGE DeriveGeneric #-}
{-# LANGUAGE TemplateHaskell #-}

module Main where

import qualified Data.Aeson as Ae
import qualified Data.Aeson.TH as Ae
import qualified GHC.Generics as G

-- | Foo's `ToJSON` instance is derived from `G.Generic`.
data Foo = Foo Int String
  deriving (Show, G.Generic)
instance Ae.ToJSON Foo

-- | Bar's `ToJSON` instance is derived with TH.
data Bar = Bar Int String
  deriving (Show)
Ae.deriveToJSON Ae.defaultOptions ''Bar


main :: IO ()
main = do
  let foo1 = Foo 7 "Hello"
  putStrLn $ "Foo: " ++ show foo1
  putStrLn $ "Foo Generic: " ++ show (G.from foo1)
  putStrLn $ "Foo JSON: " ++ show (Ae.encode foo1)

  let bar1 = Bar 7 "Hello"
  putStrLn $ "Bar: " ++ show bar1
  putStrLn $ "Bar JSON: " ++ show (Ae.encode bar1)
```

GHC output (correct):
```
Foo: Foo 7 "Hello"
Foo Generic: M1 {unM1 = M1 {unM1 = M1 {unM1 = K1 {unK1 = 7}} :*: M1 {unM1 = K1 {unK1 = "Hello"}}}}
Foo JSON: "[7,\"Hello\"]"
Bar: Bar 7 "Hello"
Bar JSON: "[7,\"Hello\"]"
```

GHCJS output (wrong):

```
Foo: Foo 7 "Hello"
Foo Generic: M1 {unM1 = M1 {unM1 = M1 {unM1 = K1 {unK1 = 7}} :*: M1 {unM1 = K1 {unK1 = "Hello"}}}}
Foo JSON: "[]"
Bar: Bar 7 "Hello"
Bar JSON: "[7,\"Hello\"]"
```

I haven't checked whether the `FromJSON` instances derived from `Generic` are wrong too.

**Comment by k0001** [comment]
Hmm, I forgot to mention: This is using `aeson-0.8.1.1` in GHC and `aeson-0.8.1.0` in GHCJS. I'll try with the most recent version from github and see if this is still happening.

**Comment by k0001** [comment]
Well, I couldn't even build the example using the most recent version from Github due to an unrelated error. The same issue happens both with GHCJS and GHC.

```
Main.hs:18:1:
    No instance for (G.Generic Bar)
      arising from a use of ‘aeson-0.10.0.0:Data.Aeson.Types.Class.$gdmtoEncoding’
    In the expression:
      aeson-0.10.0.0:Data.Aeson.Types.Class.$gdmtoEncoding
    In an equation for ‘toEncoding’:
        toEncoding = aeson-0.10.0.0:Data.Aeson.Types.Class.$gdmtoEncoding
    In the instance declaration for ‘Ae.ToJSON Bar’
```

However, judging by that [this recent commit](https://github.com/bos/aeson/commit/79a9e7b3c5e7d76d2cc60410ca317259534677c1#diff-91215b88a6eeeae8ba704adfacd86b27R23), that is to be expected.

**Comment by k0001** [comment]
Commenting out the TH code: The issue with the `ToJSON` instance derived from `Generic` is still happening as of https://github.com/bos/aeson/commit/12682c0f8f6b0d6ffa6e4fb6390fecd5451f1a02 when compiled with GHCJS.

**Comment by basvandijk** [comment]
@luite this looks like a bug in GHCJS. Shall we debug this together tomorrow at ZuriHac?

**Comment by luite** [comment]
Ah that looks broken indeed. Adding `-O` makes GHCJS produce the correct result.

**Comment by luite** [comment]
`ProductSize` is giving the wrong result here

**Comment by luite** [comment]
Yep something going wrong with the nullary method there

**Comment by luite** [comment]
Minimal example that demonstrates the problem, it's definitely GHCJS (compile without optimization):

```{.haskell}
{-# LANGUAGE KindSignatures, ScopedTypeVariables #-}

import ProdSize

main :: IO ()
main = print $ (unTagged2 :: Tagged2 (Pair Unit Unit) Int -> Int) productSize
```

```{.haskell}
{-# LANGUAGE KindSignatures, ScopedTypeVariables #-}

module ProdSize where

newtype Tagged2 s b = Tagged2 {unTagged2 :: b}

data Unit     = Unit
data Pair a b = Pair a b

class ProductSize f where
    productSize :: Tagged2 f Int

instance (ProductSize a, ProductSize b) => ProductSize (Pair a b) where
    productSize = Tagged2 $ unTagged2 (productSize :: Tagged2 a Int) +
                            unTagged2 (productSize :: Tagged2 b Int)
    {-# INLINE productSize #-}

instance ProductSize Unit where
    productSize = Tagged2 1
    {-# INLINE productSize #-}
```

**Comment by luite** [comment]
fixed in ghcjs/ghcjs@50b906ccad110d7b8a6475ad4b14e1597df0887a

@basvandijk I think it's only fair that you fix the next GHCJS bug now :)

**Comment by basvandijk** [comment]
> @basvandijk I think it's only fair that you fix the next GHCJS bug now :)

:+1: 

Thanks!

**Comment by k0001** [comment]
Great! Thank you guys.
Il 31/mag/2015 11:52, "Bas van Dijk" <notifications@github.com> ha scritto:
