### ISSUE TITLE
Allow default values in derived instances

### ISSUE THREAD

**Issue by xenog** [bos/aeson#262]
I would like to have an option to create default values for some fields in derived instances. It would be helpful to avoid bloating JSON with optional boolean flags, or worse, to bloat data types with `Maybe Bool` fields.

**Comment by bos** [comment]
I'm not quite sure what you're getting at. Could you sketch out some pseudocode of what you'd like to see?

**Comment by xenog** [comment]
Sorry @bos, I forgot I added this issue and I missed your question.

I would like aeson to allow me to create automatically derived `FromJSON` instances for data structures in which certain (or all) fields would have default values if the JSON object does not contain a key for them, instead of having to wrap them in a `Maybe` box to make them optional.

A use case is when using JSON for configuration. There are usually parameters in configuration files that have reasonable defaults, and it would be good to be able to just omit them and still have a resulting Haskell data structure with default values in these fields when reading the file.
