### ISSUE TITLE
Missing `Monad(fail)` for Parser?

### ISSUE THREAD

**Issue by hvr** [bos/aeson#263]
While testing the `MonadFail` patches I've noticed (since they trigger warnings/errors) that  in [`Data.Aeson.Types.Internal`](https://github.com/bos/aeson/blob/0.8.1.1/Data/Aeson/Types/Internal.hs) there's a `Monad`-instance lacking a custom `fail` method implementation:

```haskell
-- | The result of running a 'Parser'.
data Result a = Error String
              | Success a
                deriving (Eq, Show, Typeable)

instance Monad Result where
    return = Success

    Success a      >>= k = k a
    Error path err >>= _ = Error path err
```

even though an obvious implementation may be `fail = Error`

However, the following code fragments refer to `fail` explicitly, resulting in partial definitions:

```haskell
instance MonadPlus Result where
    mzero = fail "mzero"
    mplus a@(Success _) _ = a
    mplus _ b             = b
```

```haskell
instance Monoid (Result a) where
    mempty  = fail "mempty"
    mappend = mplus
```

...was this an oversight or deliberate?

/cc @quchen

**Comment by bos** [comment]
Looks like a mistake to me. Thanks for flagging it.
