### ISSUE TITLE
Precision and rounding when encoding fractional seconds

### ISSUE THREAD

**Issue by lpsmith** [bos/aeson#274]
Why perform any rounding or truncation of fractional seconds at all?   If you simply send all available digits,  then I can truncate or round timestamps myself before I send them to your encoder.    But if you do it for me,  and I want to send more precision than your encoder supports,  then I have to bypass your encoder altogether.

**Comment by bos** [comment]
That's a legitimate question – there's not a particularly compelling reason to do it this way, except that's how it was done before :-)
