### ISSUE TITLE
Generalise FromJSON (Map k v) instances

### ISSUE THREAD

**Issue by phadej** [bos/aeson#289]
Could we change

```hs
instance FromJSON v => FromJSON (Map String v)
instance FromJSON v => FromJSON (HashMap String v)
```
to
```hs
instance (IsText k, Ord k, FromJSON v) => FromJSON (Map k v)
instance (IsText k, Eq k, Hashable k, FromJSON v) => FromJSON (HashMap k v)
```

unfortunately `Text` doesn't provided `IsText` (yet?)

**Comment by bos** [comment]
No, I've never even heard of this typeclass.

**Comment by phadej** [comment]
Could it be created inside `Aeson` for this purpose?

**Comment by mgsloan** [comment]
Incidentally, I just copy+modified a `FromJSON` instance for Map yesterday, in stack, and in the comment, described the same idea: https://github.com/commercialhaskell/stack/blob/45fa84da555c1e1a02da70d056f8286c25d68dba/src/Stack/Types/Compiler.hs#L46

Naming-wise, maybe something like `FromJSONKey` and `ToJSONKey` classes.

**Comment by phadej** [comment]
@mgsloan I agree. Having `Text -> Parser a` would be more useful than bare `Text -> a`.
