### ISSUE TITLE
Warning:  No explicit implementation for ‘toJSON’

### ISSUE THREAD

**Issue by jkarni** [bos/aeson#290]
Why has `MINIMAL toJSON` been added? It seems inconsistent with `FromJSON`, and it generates warnings for generic instances.

**Comment by Daniel-Diaz** [comment]
I can confirm this. Generic instances do generate warnings for me as well:

```
Warning:
    No explicit implementation for
      ‘aeson-0.10.0.0:Data.Aeson.Types.Class.toJSON’
    In the instance declaration for ‘ToJSON Foo’
```

**Comment by TheCrafter** [comment]
I can confirm this too.. Generic instances generate warnings!

GHC Version: 7.10.2

**Comment by TheCrafter** [comment]
I can work around the warnings by doing this:

```
instance FromJSON SampleData
instance ToJSON SampleData where
  toJSON = genericToJSON defaultOptions
```

instead of this

```
instance FromJSON SampleData
instance ToJSON SampleData
```

**Comment by basvandijk** [comment]
I removed the MINIMAL pragma for now. 

I filed a bug for GHC about this: https://ghc.haskell.org/trac/ghc/ticket/10959

**Comment by ghorn** [comment]
Is it possible to get a new hackage release for this issue?

**Comment by Norberg** [comment]
I second ghorn's comment. It would be great if there could be a new hackage release that fixes this issue.

**Comment by jkarni** [comment]
I'd love a new release too. We've had to turn off `-Werror` on CI for `servant` because of this.
