### ISSUE TITLE
0.10 causes Couldn't match expected type `Data.Text.Internal.Text' with actual type `Data.ByteString.Builder.Internal.Builder'

### ISSUE THREAD

**Issue by mantkiew** [bos/aeson#293]
I get the following error now in the code generated by Aeson.TH:

```
src\Language\Clafer\Intermediate\Intclafer.hs:392:3:
    Couldn't match expected type `Data.Text.Internal.Text'
                with actual type `Data.ByteString.Builder.Internal.Builder'
    In the first argument of `(Data.Aeson..=)', namely
      `aeson-0.10.0.0:Data.Aeson.Encode.Builder.text
         (Data.Text.pack "gcard")'
    In the first argument of `(<$>)', namely
      `(aeson-0.10.0.0:Data.Aeson.Encode.Builder.text
          (Data.Text.pack "gcard")
        Data.Aeson..=)'

src\Language\Clafer\Intermediate\Intclafer.hs:400:3:
    Couldn't match expected type `Data.Text.Internal.Text'
                with actual type `Data.ByteString.Builder.Internal.Builder'
    In the first argument of `(Data.Aeson..=)', namely
      `aeson-0.10.0.0:Data.Aeson.Encode.Builder.text
         (Data.Text.pack "iType")'
    In the first argument of `(<$>)', namely
      `(aeson-0.10.0.0:Data.Aeson.Encode.Builder.text
          (Data.Text.pack "iType")
        Data.Aeson..=)'
```

the fields `gcard` and `iType` are 

[` , _gcard :: Maybe IGCard`](https://github.com/gsdlab/clafer/blob/master/src/Language/Clafer/Intermediate/Intclafer.hs#L89)

and 

[`_iType :: Maybe IType`](https://github.com/gsdlab/clafer/blob/master/src/Language/Clafer/Intermediate/Intclafer.hs#L144).

The error occurs on [line 392](https://github.com/gsdlab/clafer/blob/master/src/Language/Clafer/Intermediate/Intclafer.hs#L392) and [line 400](https://github.com/gsdlab/clafer/blob/master/src/Language/Clafer/Intermediate/Intclafer.hs#L400).

**Comment by juodaspaulius** [comment]
Yep, I was having the same issue and had to downgrade to 0.9.0.1..

**Comment by s9gf4ult** [comment]
I have the same issue.

**Comment by Daniel-Diaz** [comment]
I ran into the same issue. An instance that used to work, it breaks on ``aeson-0.10.0.0``. At the moment, I am building against 0.9.0.1, but I would like to build my package using the newest version. What is necessary to do in order to adapt to the new aeson?

**Comment by ankhers** [comment]
I'm also seeing this issue. 

It has something to do with `omitNothingFields = True`. If you remove that option, things should compile normally.

**Comment by basvandijk** [comment]
This should be fixed by 159de4febdb5f7170b6f226d0776ce7965af6e52. @bos will you do the release honours?

**Comment by mantkiew** [comment]
I confirm that it's fixed with HEAD (latest [commit](4de5a203eeeea593457bc92bc40062f3ea830426) ). New bug fix release please? LTS-4.0 contains `aeson-0.10.0.0`.

**Comment by Osager** [comment]
@ankhers 
I am still having the exact issue with LTS-4.1

**Comment by bergmark** [comment]
@Osager since that is an old LTS version it contains an old version of aeson without the fix. lts-4 was also discontinued early in favor of lts-5 reverting to aeson 0.9.* (which doesn't have this problem either).
