### ISSUE TITLE
Generating nested objects with new toEncoding

### ISSUE THREAD

**Issue by ondrap** [bos/aeson#301]
I have a type where the Json instance should be slightly more complex:

    instance ToJSON EsBulkDescr where
       toJSON (EsBulkDescr {esdIndex=idx, esdMapping=emap, esdId=msgId}) =
           object [ "index" .= object [ "_index" .= idx, "_type" .= emap, "_id" .= msgId ]]

I would expect, the toJSON should translate into something like:

       toEncoding (EsBulkDescr {esdIndex=idx, esdMapping=emap, esdId=msgId}) =
           pairs ( "index" .= pairs ("_index" .= idx <> "_type" .= emap <> "_id" .= msgId ))

However, I just didn't find a way to do it without creating new datatype for the embedded substructure. Would there be a way to make Encoding (or Series??) a ToJSON instance, so this could be supported? I have provisionally implemented this and it works, but maybe there is some better way:

    instance ToJSON Encoding where
       toJSON = error "Unimplemented"
       toEncoding = id

**Comment by ondrap** [comment]
I did some more hacking and it seems to me more is needed:

* I think `Encoding` should not be instance of `Monoid`. I don't think there is a valid use outside of internals of aeson - I guess you can probably easily create invalid JSON by concatenating 2 encodings
* `Encoding` should have `ToJSON` instance (I don't like the `toJSON`error, but if it is supposed to be deprecated in the future, it seems to me relatively OK)
* It would be great to have some 'unsafe' functions to access the underlying bytestring builder; e.g. to implement the base64 encoding for bytestrings I have to convert to `Text` and the `encodeUtf8` it and escape it, wheras all 3 steps could be skipped if there was an unsafe access function to the builder.

**Comment by dylex** [comment]
I think this can all be done much better by just exposing a single function that is a specialized variant of `(.=)`:
```
somethingKeyEncodingSeries :: Text -> Encoding -> Series
somethingKeyEncodingSeries name value = Value $ Encoding $ E.text name <> B.char7 ',' <> fromEncoding value
```
Obviously it needs a better name, but once you had this, you could just replace the first `.=` with it to fix everything, without needing any extra broken instances or removing the `Monoid`.

**Comment by dylex** [comment]
It would also be nice to have a version of `foldableEncoding :: Foldable t => t Encoding -> Encoding` to do the equivalent for arrays.

**Comment by ondrap** [comment]
Is there any legal use for the Monoid instance of Encoding? It seems to me that the only use is for generating invalida json output.

**Comment by bergmark** [comment]
I don't understand why the Monoid instance is there either. 

I think we should dig in and make sure that all the plubming aeson needs to create encodings internally is accessible from the outside rather than doing ad-hoc changes here and there.

Some starting points:
* We now have an exposed `unsafeToEncoding`
* There are also a bunch of un-exposed helpers in `Data.Aeson.Encode.Functions`

**Comment by phadej** [comment]
There aren't `Monoid` instance anymore. I try to think how to do

```hs
toEncoding (EsBulkDescr {esdIndex=idx, esdMapping=emap, esdId=msgId}) =
    pairs ( "index" .= pairs ("_index" .= idx <> "_type" .= emap <> "_id" .= msgId ))
```

Now we have two instances of `(.=)`:
```hs
(.=) :: ToJSON a => Text -> a -> (Text, Value) -- aka Pair
(.=) :: ToJSON a => Text -> a -> Series
```
and we'd need
```hs
(.=) :: Text -> Encoding -> Series
```
or alternatively a new operator for that.

Now we actually have a function for that: `Data.Aeson.Encoding.pair`: https://github.com/bos/aeson/blob/68bb89f0c58796fdd6d2c136c9ea3ef9b70b8685/Data/Aeson/Encoding/Internal.hs#L128

So example could be done with:

```hs
toEncoding (EsBulkDescr {esdIndex=idx, esdMapping=emap, esdId=msgId}) =
    pairs ( pair "index" $ pairs ("_index" .= idx <> "_type" .= emap <> "_id" .= msgId ))
```

**Comment by ondrap** [comment]
So it seems to me this issue can be closed - there is no Monoid instance anymore, the nested encoding can be easily done using `pair`, `unsafeToEncoding` is available. Thanks, good work!
