### ISSUE TITLE
Aeson does not escape control characters in json strings

### ISSUE THREAD

**Issue by Paczesiowa** [bos/aeson#304]
According to http://www.json.org/ strings in json values should not contain control characters unescaped, but this program:

Data.Aeson.encode (Data.Aeson.Array $ Data.Vector.fromList [Data.Aeson.String $ Data.Text.pack "\x96"])

returns this: "[\"\194\150\"]" instead of "[\"\\u0096\"]". This leads to problems when using json to interoperate with other systems, where foreign json parser does not accept such values.

Following code (for Builder module) fixes it, but I have no idea how to do it in an efficient way without going through intermediate string value:

unquoted :: T.Text -> Builder
unquoted = BP.primMapListBounded go . T.unpack
  where go = BP.condB isControl (BP.liftFixedToBounded hexEscapeChar) $
               BP.condB (> '\x7f') BP.charUtf8 (c2w >$< escapeAscii)

hexEscapeChar :: BP.FixedPrim Char
hexEscapeChar = (\c -> ('\\', ('u', fromIntegral $ ord c))) BP.>$<
        BP.char8 >*< BP.char8 >*< BP.word16HexFixed

**Comment by bos** [comment]
According to RFC 7159, the only control characters that must be escaped are [quotation mark, reverse solidus, and the control characters (U+0000 through U+001F)](https://tools.ietf.org/html/rfc7159#section-7). Whatever is trying to decode aeson's encoding is broken.
