### ISSUE TITLE
Enclosing member names in JSONPath

### ISSUE THREAD

**Issue by 0x777** [bos/aeson#311]
Current, `aeson-0.10.0.0`
````haskell
Prelude M A> A.eitherDecode "{\"a.b\" : \"c\"}" :: Either String (M.HashMap String Int)
Left "Error in $.a.b: expected Int, encountered String"
````

Expected [[ref](https://groups.google.com/forum/#!topic/jsonpath/7YvgXWP1_7Y)]
````haskell
Prelude M A> A.eitherDecode "{\"a.b\" : \"c\"}" :: Either String (M.HashMap String Int)
Left "Error in $.['a.b']: expected Int, encountered String"
````

A `key`, regardless of its contents, if defensively enclosed as `['key']`, solves this problem. Otherwise, presence of `.` can be tested and `key` can be enclosed accordingly.

**Comment by bergmark** [comment]
I think this makes sense, I'd like keys to only be escaped if they contain a period.

**Comment by phadej** [comment]
I guess it makes sense to escape if the key isn't valid jsonpath identifier (cannot find a grammar by quick googling). At least `['escapeme']` key should be escaped (how?).
