### ISSUE TITLE
Missing modules on Hackage aeson-0.10.0.0

### ISSUE THREAD

**Issue by epsilonhalbe** [bos/aeson#312]
It seems that aeson-0.10 is missing the following files
`tests/DataFamilies/{Instances,Properties}.hs`

```
> cabal get aeson
> cd aeson-0.10.0.0
> tree tests
tests
├── DataFamilies
│   ├── Encoders.hs
│   └── Types.hs
├── Encoders.hs
├── Functions.hs
├── Instances.hs
├── Options.hs
├── Properties.hs
├── Tests.hs
├── Types.hs
└── UnitTests.hs
```

Copying them from the git repository, allows the `cabal test` to run without errors

**Comment by statusfailed** [comment]
I think this has been fixed in this commit: https://github.com/bos/aeson/commit/f012d0936808224d82150292c2b866fc5d1c182c

This is also breaking the nixos package (it tries to build and run tests, so it doesn't succeed).
Tests seem to run successfully now; presumably a release would fix this?
