### ISSUE TITLE
aeson-0.10.0.0 - encoding of UTCTime values

### ISSUE THREAD

**Issue by epsilonhalbe** [bos/aeson#313]
I experience a problem in the Hackage edition of aeson 0.10.0.0

If I take the following expression
```
Prelude > import Data.Aeson
Prelude Data.Aeson > import Data.Time
Prelude Data.Aeson Data.Time > x <- getCurrentTime
Prelude Data.Aeson Data.Time > decode (encode [x]) :: Maybe [UTCTime]
Nothing
```

while the current Master succeeds.

Funny enough if you fix the test suite (see #312) by copying the missing files the test suite reports an OK.

a minimal test property (in the style of tasty) could be

```
prop_encode_decode = testProperty "encoding -> decoding for UTCTime" $ \x -> Just ([x :: UTCTime]) == decode (encode [x])
```

**Comment by dzhus** [comment]
Can confirm, `UTCTime` is not properly quoted:

```
Data.Aeson Data.Time> encode now
"2015-11-09T19:15:53.295211Z"
```

(It should be `"\"2015-11-09T19:15:53.295211Z\""` instead)

**Comment by dzhus** [comment]
I believe it was fixed in 0b98185573fd1b1656e519861b8754e6b870802c. Can we see a release please?

**Comment by epsilonhalbe** [comment]
I checked with manual escaping everything works fine
```
Prelude > :set -XOverloadedStrings
Prelude > import Data.Aeson as A
Prelude Data.Aeson > import Data.Time
Prelude Data.Aeson Data.Time > import Data.Monoid
Prelude Data.Aeson Data.Time Data.Monoid > x <- getCurrentTime
Prelude Data.Aeson Data.Time Data.Monoid > decode ("[\""<>encode x<>"\"]") :: Maybe [UTCTime]
Just [2015-11-10 08:52:21.21633 UTC]

**Comment by jkr** [comment]
Might not be the best venue for this, but is there any easy way to work around this issue until a new release comes out? I'm currently just wrapping `data UTCTime' = UTCTime' UTCTime` and defining an instance on that with the default and `constructTagModifier` wrapping it in quotes. This just seemed like the easiest to remove when a new release comes out. But is there some more straightforward approach I'm missing?

**Comment by jkr** [comment]
... or, I suppose, just hold the version at `<0.10` in the cabal file. That seems to work. Sorry for the noise.

**Comment by epsilonhalbe** [comment]
jkr - or you can just use this version on github - that seems to work allright

**Comment by bos** [comment]
I'm going to close this as it's fixed. Sorry for the inconvenience. 0.11 will be out hopefully by the end of the month.
