### ISSUE TITLE
Add ‘FromJSON’ and ‘ToJSON’ instances for ‘Numeric.Natural’

### ISSUE THREAD

**Issue by mrkkrp** [bos/aeson#318]
There is [`Numeric.Natural`](https://hackage.haskell.org/package/base-4.8.1.0/docs/Numeric-Natural.html) in `base` beginning with 4.8 version. I think it would be good to add instances of `ToJSON` and `FromJSON` for it.

**Comment by basvandijk** [comment]
Agreed. Care to submit a PR?

Make sure to surround the instances with a

#if MIN_VERSION_base(4,8,0)
...
#endif

**Comment by basvandijk** [comment]
This is fixed by #319.
