### ISSUE TITLE
Naked values emitted but not parsed in default instances

### ISSUE THREAD

**Issue by ygale** [bos/aeson#327]
The default `ToJSON` and `FromJSON` instances are not consistent:

    Aeson> encode False
    false
    Aeson> decode "false" :: Maybe Bool
    Nothing
    Aeson> decode "[false]" :: Maybe [Bool]
    Just [False]

Similar for `Int`, etc.

**Comment by tolysz** [comment]
Technically `decode` might be correct as for Json `Value` the top level can be only `Object` or `Array`.
But you are right :) `encode` should be fail if the result is not `[] or {}`.

**Comment by ygale** [comment]
The [JSON standard](http://www.ecma-international.org/publications/files/ECMA-ST/ECMA-404.pdf) does not clearly define a top-level JSON expression. But in my opinion, after a careful reading, any JSON value is allowed at the top level, not just object or array. So `encode` is correct, and `decode` should be fixed to allow any JSON value.

**Comment by tolysz** [comment]
https://www.ietf.org/rfc/rfc4627.txt
section 2.
But agree, the new RFC: https://tools.ietf.org/html/rfc7159 is more open ;) 
I really hope for one extra internal state in the `Value` (I really hope they will say - you can have an empty state internally...)

**Comment by ygale** [comment]
Yes, I see. rfc7159 explicitly states that its main purpose is to "remove inconsistencies with other specifications of JSON". The only other specifications mentioned are EMCA where the restriction on top-level values does not exist.

**Comment by bos** [comment]
I don't know which version of aeson you're reporting this bug against (hint, hint!), but this bug should no longer be valid as of 0.10 or so.

```.haskell
>>> decode "false" :: Maybe Bool
Just False
```
