### ISSUE TITLE
Release with 0.10 patches?

### ISSUE THREAD

**Issue by bergmark** [bos/aeson#328]
We are having a bit of a problem with stackage. Some packages have upgraded to aeson 0.10, but some are blocked by issues, for example #293 which is already fixed.

Our current plan is to ship LTS Haskell 4 soon after new year and the choice of excluding packages blocked by bugs, or excluding packages that have upgraded to (and require) the latest aeson version is an unpleasant one.

Would it be possible to get a minor release at least containing already merged issues soon? It would be super helpful.

Cheers!

**Comment by wereHamster** [comment]
ping

**Comment by bos** [comment]
I'm preparing a 0.11 release.

**Comment by bergmark** [comment]
That's great, thank you Bryan!

**Comment by bergmark** [comment]
Done.
