### ISSUE TITLE
ToJSON1 & FromJSON1

### ISSUE THREAD

**Issue by phadej** [bos/aeson#352]
While playing with https://github.com/bos/aeson/pull/341 I really missed these classes, as in http://hackage.haskell.org/package/transformers-0.5.1.0/docs/Data-Functor-Classes.html

```hs
class FromJSON1 f where
  liftParseJSON :: (Value -> Parser a) -> Value -> Parser (f a)

parseJSON1 :: (FromJSON1 f, FromJSON 1) -> Value -> Parser (f a)
parseJSON1 = liftParseJSON parseJSON

class ToJSON1 f where
  liftToJSON :: (a -> Value) -> f a -> Value

  liftToEncoding :: (a -> Encoding) -> f a -> Encoding
  -- Unfortunately there cannot be default implementation using 'liftToJSON'

toJSON1 :: (ToJSON1 f, ToJSON a) -> f a -> Value
toJSON1 = liftToJSON toJSON

toEncoding1 :: (ToJSON1 f, ToJSON a) -> f a -> Encoding
toEncoding1 = liftToEncoding toEncoding
```

Actually `ToJSON2` and `FromJSON2` would be useful too, their instance for tuple and `Either`.

Those could live in separate package, but then as they are more general (`parseJSON1` is not `FromJSON1` method), it would mean reimplementing many instances (and internals).

**Comment by bergmark** [comment]
Sounds good to me!

**Comment by andrewthad** [comment]
I also like this idea.

**Comment by RyanGlScott** [comment]
I'd be willing to write the grimy Template Haskell and generics code for this, if someone else writes the grimy internals and instances :)

**Comment by phadej** [comment]
I planned to work on 0.12 features when 0.11 hits Stackage.

**Comment by bergmark** [comment]
Cool! I think Jens is upgrading aeson in nightly tomorrow.

**Comment by bergmark** [comment]
This has been merged.
