### ISSUE TITLE
Restore some overlapping instances?

### ISSUE THREAD

**Issue by bergmark** [bos/aeson#355]
I re-ran @DanBurton's script to test stackage nightly against aeson's master. There were very few problems! The only thing that's not obvious to me is whether to make a few instances overlappable again (all instances were in a module with OverlappingInstances and IncoherentInstances in 0.9). 

Here are the results:

Total number of packages depending on aeson: 222

Needed external dependencies so I didn't test them: arbtt, hOpenPGP, hopenpgp-tools, ihaskell-aeson, ihaskell, inline-r, ipython-kernel

Dependency failed: yesod-mangopay (depends on mangopay)

Trivial to fix: aeson-extra, aeson-compat, ndjson-conduit

Overlapping instances:
* argon: overlaps `(ToJSON a, ToJSON b) => ToJSON (a, b)`
* haskell-neo4j-client: overlaps `ToJSON a => ToJSON (Maybe a)` & `ToJSON a => ToJSON (Maybe a)`
* mangopay: overlaps `(FromJSON a, FromJSON b) => FromJSON (Either a b)`
* pagerduty: overlaps `(FromJSON a, FromJSON b) => FromJSON (a, b)`
* stack: overlaps `(FromJSON a, FromJSON b) => FromJSON (a, b)`

**Comment by bergmark** [comment]
aeson doesn't have to be changed for overlapping instances, it's enough that the libraries needing it use `OVERLAPPING`. For the few libraries needing incoherent instances this isn't the case, there the aeson instances need to be `INCOHERENT` (which implies `OVERLAPPING`). But I don't think we should encurage incoherent instances so I'm leaning towards leaving everything as is.

**Comment by DanBurton** [comment]
What are the implications of not using incoherent instances? What was the original justification for using them? What's the recommended upgrade path for people who used to rely on the incoherent instances?

**Comment by bergmark** [comment]
> What are the implications of not using incoherent instances? 

Some instances will no longer be allowed because of this, e.g. `ToJSON (Either a Foo)` which would need `ToJSON (Either a b)` to be incoherent.

It seems the only affected stackage package is pagerduty which defines `FromJSON (b, Maybe Pager)`.

> What was the original justification for using them? 

The only place it's needed is for the `[Char]` instances and I would guess that all other instances were accidentally incoherent because they are all defined in the same module.

> What's the recommended upgrade path for people who used to rely on the incoherent instances?

Probably to use a newtype instead.

**Comment by DanBurton** [comment]
Sounds good to me.

**Comment by bergmark** [comment]
I will keep it as is.
