### ISSUE TITLE
JSONPath: The instance for Seq a doesn't track index

### ISSUE THREAD

**Issue by neongreen** [bos/aeson#358]
~~~
> eitherDecode "[1,2,true]" :: Either String (Seq Int)
Left "Error in $: expected Int, encountered Boolean"

> eitherDecode "[1,2,true]" :: Either String [Int]
Left "Error in $[2]: expected Int, encountered Boolean"
~~~

(I think this is the last incorrect instance; sorry for the noise!)

**Comment by bergmark** [comment]
It's not noise, thanks!

**Comment by neongreen** [comment]
I think it can be fixed by changing the `Seq` instance (here: https://github.com/bos/aeson/blob/master/Data/Aeson/Types/Instances.hs#L513) from

~~~ haskell
parseJSON = withArray "Seq a" $ traverse parseJSON . Seq.fromList . V.toList
~~~

to 

~~~ haskell
parseJSON = withArray "Seq a" $ 
  fmap Seq.fromList . Tr.sequence . zipWith parseIndexedJSON [0..] . V.toList
~~~

(similarly to how it's done with `[a]`), but I'm not sure whether it's the best way. If there's nothing obviously wrong with it, I can make a pull request.

**Comment by bergmark** [comment]
Looks good to me!

Please send a pull request, and please add a test case as well.
