### ISSUE TITLE
Number is not normalized before encode

### ISSUE THREAD

**Issue by notogawa** [bos/aeson#369]
0 has decimal part like 0.0, when convert floating point number (Float, Double) 0 to JSON and then encode it. Other floating point numbers which have no decimal part have no decimal part. I think 0 should be 0, not 0.0, in the same way as others.

~~~~
> encode $ toJSON ([0,1,2,0] :: [Scientific])
"[0,1,2,0]"
> encode $ toJSON ([0,1,2,0] :: [Double])
"[0.0,1,2,0.0]"
~~~~

A `base10Exponent` of Scientific value converted from floating point number 1,2,... is 0.

~~~~
> let n = fromFloatDigits (1 :: Double)
> n
1.0
> coefficient n
1
> base10Exponent n
0
~~~~

In the case 0, `base10Exponent` is -1. Scientific value converted from floating point 0 is not normalized.
Scientific says its internal expression is not necessarily normalized.

~~~~
> let z = fromFloatDigits (0 :: Double)
> z
0.0
> coefficient z
0
> base10Exponent z
-1
~~~~

So, when use internal expression like `coefficient` and `base10Exponent`, `Scientific.normalize` is required as preprocessing.

~~~~
> let x = normalize z
> x
0.0
> coefficient x
0
> base10Exponent x
0
~~~~

Especially, current `Data.Aeson.Encode.Builder.number` implicitly assumes that the argument value is already normalized.

**Comment by bergmark** [comment]
This sounds like a good improvement to me

**Comment by basvandijk** [comment]
I think the best way to solve this is to have a special case for 0 in the definition of [fromFloatDigits](https://github.com/basvandijk/scientific/blob/master/src/Data/Scientific.hs#L610) that returns (0 :: Scientific).

What do you people think? Shall I add that?

**Comment by basvandijk** [comment]
I released [scientific-0.3.4.6](http://hackage.haskell.org/package/scientific-0.3.4.6) with my proposed change.

**Comment by notogawa** [comment]
Thx. scientific-0.3.4.6 works good.

~~~~
> let x = fromFloatDigits (0 :: Double)
> x
0.0
> coefficient x
0
> base10Exponent x
0
~~~~

**Comment by bergmark** [comment]
:+1:
