### ISSUE TITLE
No documentation links on Hackage version 0.11.1.1

### ISSUE THREAD

**Issue by 2016rshah** [bos/aeson#372]
In [version 0.11.1.0](https://hackage.haskell.org/package/aeson-0.11.1.0), you can click on the modules on Hackage to be taken to documentation

![screen shot 2016-03-13 at 12 16 17 pm](https://cloud.githubusercontent.com/assets/6821244/13729865/84297b78-e915-11e5-96c8-11cecd4fbbfd.png)

However, those same links dissappear in [version 0.11.1.1](https://hackage.haskell.org/package/aeson-0.11.1.1):
![screen shot 2016-03-13 at 12 16 06 pm](https://cloud.githubusercontent.com/assets/6821244/13729871/9cefe44e-e915-11e5-94f4-2fa10264369f.png)

**Comment by neongreen** [comment]
The docs just haven't been built yet – sometimes it takes Hackage several days to build a package and render its docs.

**Comment by 2016rshah** [comment]
Oh okay, makes sense!
