### ISSUE TITLE
FromJSON/ToJSON instances in haddocks

### ISSUE THREAD

**Issue by andrewthad** [bos/aeson#375]
I'm not sure why all of the instances for `FromJSON` and `ToJSON` were moved into an internal module (I assume there was a good reason), but it's now impossible to find these instances from the haddocks.

**Comment by bergmark** [comment]
That's unfortunate. I don't know either as the offending commit (260a7e839bfda660bb7e0b715567b35d76cc4693) doesn't explain.

**Comment by bergmark** [comment]
An alternative solution to merge the modules again is expose this module and make use of https://github.com/haskell/haddock/pull/449

**Comment by phadej** [comment]
I'd guess that's somehow related to the haddock (bug or feature?), because at least haddock used to bundle orphan instances if class was exported too:
- http://hackage.haskell.org/package/binary-orphans-0.1.0.0/docs/Data-Binary-Orphans.html has `Binary Value` under `Binary` list, but
- http://hackage.haskell.org/package/binary-orphans-0.1.4.0/docs/Data-Binary-Orphans.html doesn't.

**Comment by andrewthad** [comment]
If it's a bug, it's been this way for at least a year. Because `Day` from [Data.Time.Calendar](http://hackage.haskell.org/package/time-1.6/docs/Data-Time-Calendar.html) has the exact same problem. There's a `Show` instance orphaned somewhere else, and it's exported, but not documented.

**Comment by andrewthad** [comment]
If I understand correctly, the situation we are in is summed up by the following two statements:

- We don't know why all the instances were orphaned
- Haddock currently does not show orphan instances

I would have assumed that the instances were orphaned so that the `FromJSON`/`ToJSON` combinators that they use (like `.:` and `.:?`) wouldn't need to be defined in the same module. Because without orphan instances, a class and its instances and any combinators (that mention the class) used by the instances all have to be defined in the same module.

But, I looked into it a little more and found that this wasn't the reason why this was done. All of the combinators are [still defined in the `Data.Aeson.Types.Instances` module](https://github.com/bos/aeson/blob/7da420a73632b8e3b24536da73ad7020be584849/Data/Aeson/Types/Instances.hs#L1677). So the only benefit of the split that I can see was that 1700 lines of instances (and combinators) were able to be moved out the the `Class` module.

I checked in on `Data.Aeson.Types.Generic` as well (because it provides the orphan instances for `GFromJSON` and `GToJSON`), and it seems like in that case the benefit is that 600 more lines of instances are separated from the class definitions.

My take on this whole situation is that I don't think the benefits of these orphan instances are worth the documentation difficulties. I would much rather have one large module (with very well defined sections) that has everything from `Data.Aeson.Types.Class`, `Data.Aeson.Types.Instances`, and `Data.Aeson.Types.Generic` in it. What do you guys think?

**Comment by bergmark** [comment]
Naively merging the modules isn't possible, several cyclic dependencies arise and merging these as well causes name clashes. There's for instance a Parser for every Builder with the same name.

**Comment by andrewthad** [comment]
Those are good concerns. The name clashing issue could be resolved by renaming. Concerning the cyclic import problem, here are aeson's modules:

![Aeson module graph](http://i.imgur.com/uoNpbPo.png)

The only problem that arises is that `Data.Aeson.Types.Generic` imports `Data.Aeson.Encode.Functions` which imports `Data.Aeson.Types.Class`, so flattening the first and last of these would cause an import cycle. I looked into this. Fortunately, `Data.Aeson.Types.Class` only imports one function from `Data.Aeson.Encode.Functions`: `builder`. And `builder` has a trivial one-line definition that could be copied over. I would be happy to do the work of merging the modules if this approach is approved.

**Comment by bergmark** [comment]
Okay, that sounds good to me! Please go ahead.

**Comment by andrewthad** [comment]
Cool. I'll proceed with that strategy. Thanks!

**Comment by andrewthad** [comment]
I've got the changes this here: 

It compiles fine. I accidentally did this work on top of the [List instance branch](https://github.com/bos/aeson/pull/382) instead of on master. I'm not sure how much that matters since that branch is planned to be merged anyway.

**Comment by andrewthad** [comment]
Consider this on hold until https://github.com/bos/aeson/pull/391 gets merged. I'll need to redo it on top of that branch.

**Comment by andrewthad** [comment]
@bergmark Actually, I think I should wait to redo this until right before the 0.12 release. It's impossible to cherry-pick this commit onto another branch, so I should just redo it when we're at a place where it can quickly be merged into master.

**Comment by phadej** [comment]
I'd suggest that we would work on 0.12 in the `master` branch, I hope that we can polish and merge all open pull requests, and AFAIK there are no other planned changes for `0.12`? 

If there would be a bugfix needed for `0.11` then it can be done in a branch for `0.11`. What you think, @andrewthad @bergmark ?

**Comment by bergmark** [comment]
Yes I was planning to do some merging soon. I realized we could and should make #307 backwards compatible by allowing an empty `contents` field if that isn't the case already, I'll take a closer look this weekend.

**Comment by andrewthad** [comment]
Yeah, I'm in favor of making the master branch `aeson-0.12`. It would be nice to open an issue specifically for `aeson-0.12` so that we could see a list of the planned merges and discuss any problematic merge conflicts or feature incompatibilities (although hopefully none).

**Comment by bergmark** [comment]
Sounds good, I'll create a new issue for it

**Comment by phadej** [comment]
Hmm. Would it make sense to separate `FromJSON` and `ToJSON` pairs into separate files? The obvious problem is that it's harder to make them match, or spot missing one. OTOH I'm terrified how big file we'll get when merging those (and we will add even more instances there).

**Comment by andrewthad** [comment]
@phadej I like the idea of splitting the `FromJSON` and `ToJSON` instances into separate files. That would help keep the module size down. To prevent orphan instances, we would need one file with the classes and instances for:

- `FromJSON`
- `FromJSON1`
- `FromJSON2`
- `FromJSONKey`
- `GFromJSON`

And then another file with the `ToJSON`-related typeclasses and instances. I bet there is some way we can automate looking for missing instances. With template haskell, you can look at all of the instances that are in scope for a particular typeclass. We could probably write a module that's complied as part of a test suite that just checks to make sure everything matches. @RyanGlScott Do you know if what I'm describing is possible?

But yeah, I suspect that making them match will be harder to automate.

**Comment by phadej** [comment]
@andrewthad

- the `GFromJSON` and `FromJSON` have to be in the same file: `instance (FromJSON a) => GFromJSON (K1 i a) where`
- the `FromJSON` and `FromJSON1` need to be in the same file as well
   - `parseJSON = parseJSON1`
   - `instance (ToJSON a) => ToJSON1 (Either a) where`
- also `FromJSONKey` have to be in that file `default fromJSONKeyList :: FromJSON a => FromJSONKeyFunction [a]`

So you could only split in two halves: `To` and `From` parts.

**Comment by andrewthad** [comment]
That's what I was trying to communicate. Looking back on my comment, I see that I worded things pretty poorly. :frowning:

**Comment by phadej** [comment]
Ah, sorry. :)
