### ISSUE TITLE
Can't install aeson in Mac OS through Cabal

### ISSUE THREAD

**Issue by guipdutra** [bos/aeson#379]
I'm trying to install Idris and one of the depdencies is Aeson.

Using the `cabal install aeson`. I'm getting this error.

$ cabal install aeson
Resolving dependencies...
Notice: installing into a sandbox located at
/Users/gdutra/Projects/spikes/idris/.cabal-sandbox
Configuring aeson-0.11.1.3...
Building aeson-0.11.1.3...
Failed to install aeson-0.11.1.3
Build log ( /Users/gdutra/Projects/spikes/idris/.cabal-sandbox/logs/aeson-0.11.1.3.log ):
Configuring aeson-0.11.1.3...
Building aeson-0.11.1.3...
Preprocessing library aeson-0.11.1.3...
[ 1 of 16] Compiling Data.Aeson.Functions ( Data/Aeson/Functions.hs, dist/dist-sandbox-9d532b70/build/Data/Aeson/Functions.o )
[ 2 of 16] Compiling Data.Aeson.Internal.Time ( Data/Aeson/Internal/Time.hs, dist/dist-sandbox-9d532b70/build/Data/Aeson/Internal/Time.o )
[ 3 of 16] Compiling Data.Aeson.Types.Internal ( Data/Aeson/Types/Internal.hs, dist/dist-sandbox-9d532b70/build/Data/Aeson/Types/Internal.o )

Data/Aeson/Types/Internal.hs:401:28:
    Not in scope: ‘foldl'’
    Perhaps you meant one of these:
      ‘H.foldl'’ (imported from Data.HashMap.Strict),
      ‘V.foldl'’ (imported from Data.Vector),
      ‘foldl’ (imported from Prelude)
cabal: Error: some packages failed to install:
aeson-0.11.1.3 failed during the building phase. The exception was:
ExitFailure 1

**Comment by guipdutra** [comment]
Update: I could install a old version

`cabal install aeson-0.11.1.1`

**Comment by bergmark** [comment]
Sounds like #377 could be the culprit.

This is not enough information for me to reproduce the issue. What GHC version are you using? Are you able to reproduce this in a new sandbox? Please give the full log with `-v` passed to cabal install

**Comment by guipdutra** [comment]
full log cabal install:

https://gist.github.com/guipdutra/007ca0b8cf6fa2304716

**Comment by bergmark** [comment]
Thank you. It seems to be the combination of GHC >= 7.10 and unordered-containers < 0.2.6 that causes this.

**Comment by bergmark** [comment]
I just released aeson-0.11.1.4 with a fix.

**Comment by guipdutra** [comment]
Thank you :)
