### ISSUE TITLE
Document Series

### ISSUE THREAD

**Issue by andrewthad** [bos/aeson#383]
In [aeson-0.11.1.4](http://hackage.haskell.org/package/aeson-0.11.1.4/docs/Data-Aeson.html), there is a type named Series. From the haddocks, I can see that the data constructors are not exported it has instances for Monoid and Semigroup. There's a function name `pairs` that consumes a `Series` and produces an `Encoding`. But, the missing piece is how to create a `Series`. With `mempty`, I could create an empty one, but then I'm stuck. I assume that there are some orphaned instances that aren't showing up in the haddocks, but even with all instances properly showing, it would be nice to have a few sentences on the use-case that this data type satisfies.

**Comment by bergmark** [comment]
To me it seems like something is missing from the public API. The obvious addition would be `something :: Encoding -> Series`, is that how you would like to use it?

**Comment by andrewthad** [comment]
I don't really know how I would like to use it or if it's even something I need. I just haven't been able to figure out what it's supposed to do. If there is a function that goes from `Encoding -> Series`, then that would give us a way to use it, and I think that would make it more clear what it's used for.

**Comment by bergmark** [comment]
I dug a bit and noticed this instance which looks sufficient:

```haskell
-- | A key-value pair for encoding a JSON object.
class KeyValue kv where
    (.=) :: ToJSON v => Text -> v -> kv

instance KeyValue Series where
    name .= value = Value . Encoding $ E.text name <> B.char7 ':' <> builder value
```

**Comment by andrewthad** [comment]
Ah, thanks. I guess this is just a another manifestation of https://github.com/bos/aeson/issues/375. Also, I would also like to see a little more documentation of `Series` as well. The documentation currently reads:

> A series of values that, when encoded, should be separated by commas.

I think that could be elaborated to something more like:

> A series of values that, when encoded, should be separated by commas. Since 0.11.0, the (.=) operator is over loaded to create either (Text,Value) or Series. You can use Series when encoding directly to a bytestring builder as in the following example:

    toEncoding (Person name age) =
        pairs ("name" .= name <> "age" .= age)

I stole that example from earlier in the docs, and I'm not super concerned with the exact wording. My main difficulty with seeing how `Series` was involved in the earlier `toEncoding` example was that the word `Series` doesn't appear anywhere near it. I think that by presenting that example again but having it right beside `Series`, it becomes more clear what it's used for.
