### ISSUE TITLE
toJSON (Just Nothing) == toJSON Nothing

### ISSUE THREAD

**Issue by Peaker** [bos/aeson#384]
The encoding of `Maybe` uses in-band `null` for `Nothing`. and thus cannot differentiate `Just Nothing` from `Nothing`.

Is this intentional?

Shouldn't we expect a law that  `fromJSON . toJSON` is like `id` (modulo the failure potential in the types)?

**Comment by Peaker** [comment]
I just noticed this is a dup!

**Comment by tomjaguarpaw** [comment]
For posterity, a dup of https://github.com/bos/aeson/issues/376
