### ISSUE TITLE
Deriving FromJSON/ToJSON for GADTs

### ISSUE THREAD

**Issue by andrewthad** [bos/aeson#385]
So, I'm working with GADTs that I'm using as instruction sets for programs with `operational`. I have GADTs that look like this:

    data RecordStoreI a where                                                                             
        LookupRecordI      :: RecordId -> RecordStoreI Record
        LookupRecordsI     :: Query -> RecordStoreI [Record]
        CreateRecordI      :: RecordBase -> RecordStoreI RecordId

GHC will not derive a `Generic` instance for GADTs, but it seems like using TH should be possible. If I add this:

    $(deriveJSON defaultOptions ''RecordStoreI)

Then I get this error:

    /home/andrew/Development/grove/logos/src/Logos/Types.hs:218:3:
        Couldn't match type ‘a’ with ‘RecordId’
          ‘a’ is a rigid type variable bound by
              the instance declaration at src/Logos/Types.hs:218:3
        Expected type: RecordBase -> RecordStoreI a
          Actual type: RecordBase -> RecordStoreI RecordId
        Relevant bindings include
          parseJSON :: Aeson.Value -> Aeson.Parser (RecordStoreI a)
            (bound at src/Logos/Types.hs:218:3)
        In the first argument of ‘(<$>)’, namely ‘CreateRecordI’
        In the expression: (CreateRecordI <$> (parseJSON arg_ahJe))

I'm about to try tweaking `deriveJSON` to see if it's possible to do this, but I figured I'd post here to see if there were any insights into the issue. (If someone has enough intuition around this to know that it's provably impossible, I would appreciate knowing).

**Comment by andrewthad** [comment]
I have found that writing `ToJSON` is possible but that writing `FromJSON` for `RecordStoreI a` is definitely impossible, even without TH.

**Comment by RyanGlScott** [comment]
Indeed, `$(deriveToJSON defaultOptions ''RecordStoreI)` works today, but I doubt you can write a `parseJSON` expression that will work for all three constructors at once.

Hypothetically, if it were possibly to restrict deriving `parseJSON` to specific constructors, I could envision something like this:

```haskell
instance FromJSON (RecordStoreI Record) where
  parseJSON = $(mkParseJSONCons defaultOptions { restrictCons = Just ['LookupRecordI] } ''RecordStoreI)

instance FromJSON (RecordStoreI [Record]) where
  parseJSON = $(mkParseJSONCons defaultOptions { restrictCons = Just ['LookupRecordsI] } ''RecordStoreI)

instance FromJSON (RecordStoreI RecordId) where
  parseJSON = $(mkParseJSONCons defaultOptions { restrictCons = Just ['CreateRecordI] } ''RecordStoreI)
```

**Comment by andrewthad** [comment]
@RyanGlScott Thanks for sharing for your thoughts. I realized that didn't even actually want what I originally thought I did. I needed to existentially quantify the type variable, since I don't actually know in advance which data constructor I'm parsing. What I ultimately settled on was doing this:

    module Data.Aeson.Existential where

    import Data.Aeson                                                                                 
    import Data.Aeson.Types

    data Hide f = forall a. Hide (f a)

    class HideFromJSON f where
      hideParseJSON :: Value -> Parser (Hide f)

    instance HideFromJSON f => FromJSON (Hide f) where
      parseJSON = hideParseJSON

And then writing my instance:

    instance HideFromJSON RecordStoreI where
       ...

Which is sufficient for my needs. I think that `hideParseJSON` is derivable with TH, but it doesn't benefit me enough to try writing it at the moment, and I can't imagine that there are that many other aeson users who would want this.

**Comment by RyanGlScott** [comment]
Ah, so you want to be able to derive something like this:

```haskell
instance HideFromJSON RecordStoreI where
  parseJSON =
    \ value_aaql
      -> case value_aaql of
           Object obj_aaqm
             -> do conKey_aaqn <- (obj_aaqm .: (Data.Text.pack "tag"))
                   case conKey_aaqn of
                     _ | (conKey_aaqn == (Data.Text.pack "LookupRecordI"))
                       -> do val_aaqo <- (obj_aaqm .: (Data.Text.pack "contents"))
                             case val_aaqo of
                               arg_aaqp -> (Hide <$> LookupRecordI <$> (parseJSON arg_aaqp))
                       | (conKey_aaqn == (Data.Text.pack "LookupRecordsI"))
                       -> do val_aaqq <- (obj_aaqm .: (Data.Text.pack "contents"))
                             case val_aaqq of
                               arg_aaqr -> (Hide <$> LookupRecordsI <$> (parseJSON arg_aaqr))
                       | (conKey_aaqn == (Data.Text.pack "CreateRecordI"))
                       -> do val_aaqs <- (obj_aaqm .: (Data.Text.pack "contents"))
                             case val_aaqs of
                               arg_aaqt -> (Hide <$> CreateRecordI <$> (parseJSON arg_aaqt))
                       | otherwise
                       -> Data.Aeson.TH.conNotFoundFailTaggedObject
                            "Ghci7.RecordStoreI"
                            ["LookupRecordI", "LookupRecordsI", "CreateRecordI"]
                            (Data.Text.unpack conKey_aaqn)
           other_aaqu -> Data.Aeson.TH.noObjectFail
                  "Ghci7.RecordStoreI" (Data.Aeson.TH.valueConName other_aaqu)
```

I agree that perhaps that wouldn't be ideal to put in `Data.Aeson.TH`, but you can at least copy-paste that code pretty easily by compiling

```haskell
$(mkParseJSON defaultOptions ''RecordStoreI)
```

with `-ddump-splices` on. Then simply add `Hide <$>`s where necessary.

(One could also envision a TH function which scans this `Exp` and splats `infixAppE (Just 'Hide) '(<$>) Nothing` where necessary.)

**Comment by andrewthad** [comment]
Nice! That's almost exactly the instance that I hand-wrote. Thanks!
