### ISSUE TITLE
Invalid JSON generated by genericToEncoding

### ISSUE THREAD

**Issue by alexanderkjeldaas** [bos/aeson#387]
`omitNothingFields` does not work for `genericToEncoding`
```haskell
> data Test = Test { x :: Maybe String, y :: Maybe String }  deriving (Generic)
> instance ToJSON Test where toEncoding =
      genericToEncoding defaultOptions {omitNothingFields = True}
> encode $ Test Nothing Nothing
"{,}"
```

**Comment by bergmark** [comment]
Thank you for the report!

This is similar to #366 but is not fixed by that PR.

**Comment by tolysz** [comment]
I do not want to say it; but we miss a constructor of `VALUE` which represents the values we want to omit. (as it is the container which needs to remove the value; not just value to emit nothing).

Without the additional constructor ( https://skillsmatter.com/skillscasts/6587-programming-with-universal-properties ) there is no way to have a function which maps 
`Null` value to 2 states at the same time.

**Comment by Tritlo** [comment]
I'm having a similar issue where when I use `omitNothingFields`, I get an empty `,`, i.e.

    data GraphResponse = GraphResponse { data :: [Value]
                                       , errors :: Maybe [Value]
                                       , info :: Maybe Value
                                       } deriving (Show, Generic, FromJSON)



    instance ToJSON GraphResponse where
      toJSON = genericToJSON defaultOptions {omitNothingFields = True}
      toEncoding = genericToEncoding defaultOptions {omitNothingFields = True}


where `GraphResponse [] Nothing Nothing` results in the `JSON` `{"data":[],,}`, i.e. with extra commas.
