### ISSUE TITLE
Expose decodeWith and friends Data.Aeson.Parser

### ISSUE THREAD

**Issue by mitchellwrosen** [bos/aeson#397]
I'd like to have access to `decodeWith`, so that I can write an aeson-style parser for a datatype for which I cannot or wish not to provide an actual `FromJSON` instance. For example,

```haskell
data Foo = ...  -- from some third-party library

fooParser :: Value -> Parser Foo
fooParser = withObject "object" $ \o -> Foo
  <$> o .: "bar"
  <*> o .: "baz"

decodeFoo :: ByteString -> Maybe Foo
decodeFoo = decodeWith fooParser
```

**Comment by bergmark** [comment]
I like the idea but your example does not type check.

I think we should expose these from `Data.Aeson.Parser` instead of exposing the whole internal module.

To be consistent with the class based decodes we should also export variants of all these functions:     , `eitherDecode, eitherDecode', decodeStrict, eitherDecodeStrict`

**Comment by mitchellwrosen** [comment]
Err, right, I missed a `jsonEOF` argument to `decodeWith`. And yeah, exposing from `Data.Aeson.Parser` is better. Do you want a PR for this?

**Comment by bergmark** [comment]
What do you want the type signature to be?

**Comment by mitchellwrosen** [comment]
Hm? I'm talking about exporting the `decodeWith` that already exists in `Data.Aeson.Parser.Internal`:

```haskell
decodeWith :: Parser Value -> (Value -> Result a) -> L.ByteString -> Maybe a                                               
decodeWith p to s =                                                                                                        
    case L.parse p s of                                                                                                    
      L.Done _ v -> case to v of                                                                                           
                      Success a -> Just a                                                                                  
                      _         -> Nothing                                                                                 
      _          -> Nothing                                                                                                
{-# INLINE decodeWith #-}
```

**Comment by bergmark** [comment]
I'm asking because the signature of `decodeWIth` in your first example would have been just `:: (Value -> Result a) -> L.ByteString -> Maybe a`. Are there use cases for passing something other than `jsonEOF` as the first argument?

**Comment by mitchellwrosen** [comment]
Ah, that was just a typo :)

And I'm not sure, I would certainly pass jsonEOF for all my needs.

**Comment by bergmark** [comment]
I ended up exporting the functions as is. Since aeson uses different arguments users may also want to.

**Comment by mitchellwrosen** [comment]
Thanks!
