### ISSUE TITLE
Encoding performance - toList Data.Sequence vs. foldable Data.Sequence

### ISSUE THREAD

**Issue by ondrap** [bos/aeson#402]
I was testing something slightly different and found out that doing `AE.encode seqVar` is about 15% slower than doing `AE.encode (toList seqVar)`. I am not sure how it works for other `Foldable` containers, however it seems to me it would make sense to change at least the `Seq` instance to:

```
toEncoding = list . toList
```

**Comment by phadej** [comment]
We should write a benchmark for this,
`list` and `foldable` encoding are implemented differently, we probably can tweak them to have same "best" performance. 

Make sense to do after https://github.com/bos/aeson/pull/391

**Comment by mgsloan** [comment]
The poor vector performance is likely due to https://github.com/haskell/vector/issues/112

**Comment by bergmark** [comment]
Marked as "need-info" as we want benchmark results.
