### ISSUE TITLE
Use base-compat and time-locale-compat to reduce CPP

### ISSUE THREAD

**Issue by phadej** [bos/aeson#406]
Opinions?

**Comment by bergmark** [comment]
I'm for this, CPP is nasty.

**Comment by bergmark** [comment]
Might make sense to wait with this until most of 0.12 is ready?

**Comment by phadej** [comment]
@bergmark yes, I'd rather do it at least after https://github.com/bos/aeson/pull/407

**Comment by RyanGlScott** [comment]
This has been fixed, yes?
