### ISSUE TITLE
Monoid/Semigroup instance for Encoding leads to misuse

### ISSUE THREAD

**Issue by snoyberg** [bos/aeson#434]
I [commented on Twitter](https://twitter.com/snoyberg/status/744485932817129472) that I was concerned about the `Monoid` instance for `Encoding`, and didn't see a justification I was happy with, so I'm raising it here. It seems that `Encoding` is intended to represent a valid JSON value, and that multiple JSON values should be appended together using `Series`. However, by using the underlying `Builder`'s `Monoid` instance, it's trivially easy to accidentally generated invalid `Encoding` values:

```haskell
#!/usr/bin/env stack
-- stack --resolver lts-6.3 runghc --package aeson
import Data.Aeson (toEncoding, fromEncoding)
import Data.Monoid ((<>))
import Data.ByteString.Builder (toLazyByteString)
import qualified Data.ByteString.Lazy.Char8 as L8

main :: IO ()
main = L8.putStr
     $ toLazyByteString
     $ fromEncoding
     $ toEncoding () <> toEncoding ()
```

I'd recommend deprecating the `Monoid` and `Semigroup` instances, and removing them in the next release of aeson.

**Comment by phadej** [comment]
It will be removed in the next major release `aeson-1`. The current state in master should be quite close to what will be released, AFAIK

**Comment by bergmark** [comment]
Yep already fixed by @phadej!

**Comment by snoyberg** [comment]
Thank you both!
