### ISSUE TITLE
Can't decode to records with multiple value constructors

### ISSUE THREAD

**Issue by bgwines** [bos/aeson#437]
Hi, there! Let's say you have a record

```{.haskell}
data DataType
    = A { a :: Int }
    | B { b :: Bool }
```

I haven't been able to successfully decode to such a data type using Aeson. Not sure if this a bug or a feature request.

I've put up an isolated 100% reproducible test case for you at https://github.com/bgwines/aeson-repro

Thanks for your attention to the matter! :)

**Comment by phadej** [comment]
sum types are encoded (by default) with `tag` field to *tag the constructor*:
```hs
λ > A.encode $ User "foo" "bar" Nothing
"{\"email\":\"bar\",\"username\":null,\"name\":\"foo\"}"
λ > A.encode $ SmallUser "foo" "bar" Nothing
"{\"email\":\"bar\",\"tag\":\"SmallUser\",\"username\":null,\"name\":\"foo\"}"
```

Currently there isn't a way to deriving untagged serialisation generically, though it could be possible to add `UntaggedObject` to [`SumEncoding`](http://hackage.haskell.org/package/aeson-0.11.2.0/docs/Data-Aeson-TH.html#t:SumEncoding). We can do it for `aeson-1` (the next major release). Opinions @bergmark ? I remember I needed similar functionality in the past too. 

So the the derived instance would be something like
```hs
instance FromJSON DataType where
    parseJSON v = parseA v <|> parseB v
      where
      	parseA = withObject "A" $ \obj -> A <$> obj .: "a"
      	parseB = withObject "B" $ \obj -> B <$> obj .: "b" 
```

**Comment by bergmark** [comment]
Sure this is a reasonable thing to have, I've used similar instances.
