### ISSUE TITLE
`FromJSON`/`ToJSON` instance lists missing from haddocks

### ISSUE THREAD

**Issue by Gabriel439** [bos/aeson#438]
For some reason the instance lists for `FromJSON`/`ToJSON` don't render at all for the more recent versions of `aeson`, which makes it a bit difficult to figure out what instances are available.  The workaround at the moment is to browse the instance lists for an older version of the library.

**Comment by phadej** [comment]
This is duplicate of https://github.com/bos/aeson/issues/375. Will be fixed in the next release.

**Comment by Gabriel439** [comment]
Thanks! :)
