### ISSUE TITLE
Error in comment on `.:?`

### ISSUE THREAD

**Issue by seagreen** [bos/aeson#445]
The comment [currently reads](https://github.com/bos/aeson/blob/9fcb4a023a240d7baf5df11058d04cc13aa7b6a4/Data/Aeson/Types/FromJSON.hs#L663):
```
-- | Retrieve the value associated with the given key of an 'Object'.
-- The result is 'Nothing' if the key is not present, or 'empty' if
-- the value cannot be converted to the desired type.
```

If the key is present with the value `Null` and cannot be converted to the desired type this suggests that the result will be `empty`. But in practice the result is a successful parse:
```
> let f = (\a -> a .:? "type") :: HashMap Text Value -> Parser (Maybe Bool)
> parse f (HM.singleton "type" Null)
Success Nothing
```

Also if the key is present and the value can be converted to the desired type the comment suggests that it will. But this isn't the case if the value is `Null`:
```
> data Foo = Foo deriving Show
> instance FromJSON Foo where parseJSON Null = pure Foo
> let g = (\a -> a .:? "type") :: HashMap Text Value -> Parser (Maybe Foo)
> parse g (HM.singleton "type" Null) -- Expecting `Success Foo`
Success Nothing
```

**Comment by seagreen** [comment]
(Edited the issue to add the missing `> instance FromJSON Foo where parseJSON Null = pure Foo` line)

**Comment by seagreen** [comment]
`.:!` needs improvement as well.

The [comment](https://github.com/bos/aeson/blob/9fcb4a023a240d7baf5df11058d04cc13aa7b6a4/Data/Aeson/Types/FromJSON.hs#L676):
```
-- | Like '.:?', but the resulting parser will fail,
-- if the key is present but is 'Null'.
```

The behavior:
```
> data Foo = Foo deriving Show
> instance FromJSON Foo where parseJSON Null = pure Foo
> let k = (.:? "type") :: HashMap Text Value -> Parser (Maybe Foo)
> parse k (HM.singleton "type" Null) -- Expecting failure
Success Nothing
```

**Comment by seagreen** [comment]
Also, I have a subjective question: are we missing a useful operator? It seems like `.:!` is very useful, `.:?` should be deprecated, and another operator added with the type:

`(FromJSON a) => Object -> Text -> Parser (Maybe a)`

That:

+ Returns `pure Nothing` if the value is missing
+ Returns `pure a` if the value exists and can be parsed to `a`
+ Returns `pure Nothing` if the value is `Null` and cannot be parsed to `a`
+ Fails otherwise.

But I'm not sure about this. Thoughts?

**Comment by seagreen** [comment]
@bergmark I overloaded this issue with more comments, want to reopen it or should I bring them up as separate issues?

**Comment by phadej** [comment]
@seagreen, how combinator you proposed differ from .:?

**Comment by tolysz** [comment]
we really need an operator like `.:??`
which will have 2 actions: one if the key is missing and one if the key is null :)
( https://github.com/tolysz/aeson/blob/Missing_v10/Data/Aeson/Types/Instances.hs#L1657 )

**Comment by seagreen** [comment]
`.:?` works as follows -- I think, I'm trying to be careful here but these are a little tricky:)

+ Returns `pure Nothing` if the value is missing.
+ Returns `pure Nothing` if the value is `Null`
+ Returns `pure (Just a)` if the value exists and can be parsed to `a`.
+ Fails otherwise.

So the difference between the new operator and `.:?` would be that the new operator would try to parse `Null`s to `Just a` before returning them as `Nothing`, while `.:?` always returns `Null`s as `Nothing`, even if they could be successfully parsed to data.

Now that I write this out I find I'm liking the behavior of `.:?` more: I like I how explicit it is in grabbing the meaning of `Null` and turning it into missing values. The only time this could be a problem is if you're identifying missing values by using `Null` instead of omitting keys, and later you add a datatype that can be serialized/deserialized from `Null`. I think the correct response here is "try not to do that" so I don't think there's any need to provide a function to help someone make bad decisions.
