### ISSUE TITLE
Record field `tag` used in sum causes trouble.

### ISSUE THREAD

**Issue by raichoo** [bos/aeson#456]
Hi,

I've stumbled across this behavior, while I know that using record fields in a sum isn't good style this
should be avoidable.

``` haskell
{-# LANGUAGE DeriveGeneric #-}
module AesonTag where

import Data.Aeson

import GHC.Generics

data Foo
  = Bar Int
  | Quux { tag :: Bool }
  deriving (Generic, Show)

instance FromJSON Foo
instance ToJSON   Foo

test :: IO ()
test = do
  let x = Bar 1337
      y = Quux True

  print (encode x) -- "{\"tag\":\"Bar\",\"contents\":1337}"
  print (decode (encode x) :: Maybe Foo) -- Just (Bar 1337)
  print (encode y) -- "{\"tag\":true}"
  print (decode (encode y) :: Maybe Foo) -- Nothing
```

Naming the record field `tag` overwrites the `Quux` tag that I would expect here which is causing trouble with decoding.

Kind regards,
raichoo

**Comment by phadej** [comment]
The documentation for [`SumEncoding`](http://hackage.haskell.org/package/aeson-0.11.2.0/docs/Data-Aeson-Types.html#t:SumEncoding) talks about this:

> A constructor will be encoded to an object with a field tagFieldName which specifies the constructor tag (modified by the constructorTagModifier). If the constructor is a record the encoded record fields will be unpacked into this object. So make sure that your record doesn't have a field with the same label as the tagFieldName. Otherwise the tag gets overwritten by the encoded value of that field! If the constructor is not a record the encoded constructor contents will be stored under the contentsFieldName field.

In other words you should do

```hs
myOpts :: Options
myOpts = defaultOptions { sumEncoding = TaggedObject { tagFieldName = "mytag" } }
instance FromJSON Foo where
    parseJSON = genericParseJSON myOpts
instance ToJSON   Foo where
    toJSON = genericToJSON myOpts
    toEncoding = genericToEncoding = myOpts
```

**Comment by bergmark** [comment]
@raichoo do you think the existing documentation is good enough or do you have ideas how to improve it?

**Comment by raichoo** [comment]
I don't know. To be honest this is pretty much a non-issue for me since I'm not really declaring data this way, but I've been encouraged by others to file a bug report about this.

**Comment by bergmark** [comment]
Thanks,
I don't know either so I'll close this. If someone has suggestions, let's discuss!
