### ISSUE TITLE
instances for Data.Semigroup.*

### ISSUE THREAD

**Issue by lspitzner** [bos/aeson#461]
As of base-4.9/ghc-8, `base` contains `Data.Semigroup` (and aeson already depends on semigroups anyway), so the instances belong here.

One question though: I looked at the instance for `Identity` and noticed it indirects to a manual `FromJSON1` instance. What is the benefit of this? Wouldn't it completely suffice to implement FromJSON directly using `fmap Identity` and `runIdentity`? (Most stuff in semigroups is similar newtype wrappers.)

**Comment by bergmark** [comment]
Which Semigroup instances would you like to add? As far as I can tell all monoids have semigroup instances already.

**Comment by bergmark** [comment]
Oh, sorry, I realize you mean types in the semigroups package, not semigroup instances.

**Comment by bergmark** [comment]
@phadej can you answer the question about Identity?

I agree that we should add the missing instances. They can be placed next to the NonEmpty instances in `Data.Aeson.Types.ToJSON/FromJSON`. Another thing to note is that we only conditionally depend on the semigroups package so we need to make sure all these types are in both `base` and `semigroups`. I think so but I haven't checked.

 @lspitzner are you willing to work on this? It's a non-breaking addition so we can release a v1.0.1.0 whenever this is ready.

**Comment by lspitzner** [comment]
I am mildly certain that the conditionally dependency is exactly as necessary - `Data.Semigroup` will always be available, from `base` for >=ghc8 and `semigroups` for <ghc8.

Sure, i can write a PR. Would include instances for `First`, `Last`, `Option` and `WrappedMonoid`. All newtype wrappers, so the instances are trivial. Will wait for an answer from @phadej.

**Comment by phadej** [comment]
Every `FromJSON` is implemented using `FromJSON1` if there is  one, just to have consistent instances and DRY.

**Comment by phadej** [comment]
IIRC `Min` and `Max` are in base as well

**Comment by lspitzner** [comment]
ah of course, the FromToJson1 are exposed, too. Derp.

Right, will add Min/Max too.
