### ISSUE TITLE
A confusing error message mentioning (:*:) when using an autoderived instance

### ISSUE THREAD

**Issue by neongreen** [bos/aeson#474]
First of all, the error itself (it appears when you try to parse an object but your JSON isn't an object):

```
> main
Left "Error in $: expected record (:*:), encountered Boolean"
```

And the code:

``` haskell
{-# LANGUAGE OverloadedStrings #-}
{-# LANGUAGE DeriveGeneric #-}

import Data.Aeson
import GHC.Generics

data Foo = Foo {x :: Int}
  deriving (Generic, Show)

instance FromJSON Foo

main = print (eitherDecode "true" :: Either String Foo)
```

The error generated by the TH-derived instance is less likely to confuse someone who doesn't know about generics:

```
> main
Left "Error in $: When parsing the constructor Foo of type Main.Foo expected Object but got Boolean."
```

``` haskell
{-# LANGUAGE TemplateHaskell #-}
{-# LANGUAGE OverloadedStrings #-}

import Data.Aeson
import Data.Aeson.TH

data Foo = Foo {x :: Int}
  deriving (Show)

deriveFromJSON defaultOptions ''Foo

main = print (eitherDecode "true" :: Either String Foo)
```

**Comment by bergmark** [comment]
Yeah this is definitely something that can be improved.

On a higher level there is also room for discussing what default error messages should look like. The message produced by the TH includes `Main.Foo` which is only useful if you are working with json inside a haskell application that has access to the types. If you are a client talking only json to the application a more useful message might be "Error in $: Expected Object but got Boolean", or even better expanding Object to the fields it includes.

**Comment by phadej** [comment]
Hmm, I'm sure we are able to stick `withObject` somewhere in the records generic parsing
