### ISSUE TITLE
Expose <?>

### ISSUE THREAD

**Issue by bergmark** [bos/aeson#475]
Looks like it's only available from `Data.Aeson.Internal`, there are some helper functions like `Data.Aeson.Types.FromJSON.parseIndexedJSON` which aren't exposed either. The JSON paths are a really nice feature so we shouldn't keep it hidden.

Does anyone have thoughts on exposing `<?>` and `JSONPath` as is?

**Comment by bergmark** [comment]
A more robust approach might be to export smart constructors so that we aren't tied to the ADT. I'm not sure if a user wants to do anything more than just constructing the values.

**Comment by phadej** [comment]
I'd wait for someone to raise their voice, what API they would like to be exposed. For my own needs just `<?>` was enough so far.

**Comment by cblp** [comment]
I raise my voice for `<?>`

**Comment by abiduzz420** [comment]
Hi, I would like to work on this. Since this is an old issue, I want to know if this change is still a desirable one?
As a side note, I am looking to get familiar with the aeson codebase and this could well be my first patch to the library.

**Comment by Lysxia** [comment]
As far as I can tell It's still useful.

**Comment by bergmark** [comment]
please go ahead! note that i’m on vacation for a couple of weeks so merging
may be delayed.

**Comment by gdevanla** [comment]
Looks like this issue was resolved with #688. Should this issue be closed now?

**Comment by bergmark** [comment]
Yep, thanks!
