### ISSUE TITLE
Build errors on Ubuntu 14.04.

### ISSUE THREAD

**Issue by sowani** [bos/aeson#478]
Hi,

I am trying to build top-of-the-tree aeson on Ubuntu 14.04 [have a hard requirement for older version :( ] using ghc version 7.6.3 installed using "apt-get install haskell-platform". The build throws following errors:

[ 5 of 20] Compiling Data.Aeson.Types.Internal ( Data/Aeson/Types/Internal.hs, dist/build/Data/Aeson/Types/Internal.o )

Data/Aeson/Types/Internal.hs:384:17:
    Template Haskell bracket requires GHC with interpreter support
    Perhaps you are using a stage-1 compiler?
      [| Null |]

Data/Aeson/Types/Internal.hs:385:21:
    Template Haskell bracket requires GHC with interpreter support
    Perhaps you are using a stage-1 compiler?
      [| Bool b |]

Data/Aeson/Types/Internal.hs:386:23:
    Template Haskell bracket requires GHC with interpreter support
    Perhaps you are using a stage-1 compiler?
      [| Number (S.scientific c e) |]

Data/Aeson/Types/Internal.hs:390:23:
    Template Haskell bracket requires GHC with interpreter support
    Perhaps you are using a stage-1 compiler?
      [| String (pack s) |]

Data/Aeson/Types/Internal.hs:392:22:
    Template Haskell bracket requires GHC with interpreter support
    Perhaps you are using a stage-1 compiler?
      [| Array (V.fromList a') |]

Data/Aeson/Types/Internal.hs:394:23:
    Template Haskell bracket requires GHC with interpreter support
    Perhaps you are using a stage-1 compiler?
      [| Object (H.fromList . map (first pack) $ o') |]
Failed to install aeson-1.0.2.0
cabal: Error: some packages failed to install:
aeson-1.0.2.0 failed during the building phase. The exception was:
ExitFailure 1

ghc --info says among other things:
 ,("Stage","2")
 ,("Have interpreter","NO")

[Kindly let me know if more details are required about ghc --info]

If build script expects "ghci", it is missing from my system and I haven't yet figured out how to get hold of this binary. "haskell-platform" package does not seem to have this binary.

I highly appreciate any help about how I can get around this issue and get aeson built.

Thanks,
Atul.

**Comment by phadej** [comment]
Does @hvr know something about this?

**Comment by hvr** [comment]
I'm going to have to investigate; I'm a bit surprised that Ubuntu 14.04 shipped with a TH-less GHC. What architecture is this on?

However, there's little hope to build `aeson` on a TH-less GHC 7.6 (unless TH is manually removed/disabled from aeson); aeson only supports TH-less GHCs starting with GHC 8 which introduced TemplateHaskellQuotes

**Comment by sowani** [comment]
@hvr 
Thanks for looking into this. I think one more piece of information is required from me - the platform is power8/le (ppc64le).

**Comment by bergmark** [comment]
Good to hear that this isn't a problem come GHC 8. Unfortunately I don't think it's worthwhile for us to support unusual configurations on old GHC versions, GHC 7.6 was released over 4 years ago!

So upgrading GHC or monkey patching aeson should be the way to go.
