### ISSUE TITLE
GHC 8.0.1 crash from using Data.Aeson.TH

### ISSUE THREAD

**Issue by jchia** [bos/aeson#481]
I have a simple source file using Aeson TH that crashes GHC 8.0.1, although I don't know whether bad TH code crashing GHC is a feature, a bug with GHC or a bug with aeson. Compiling with `stack ghc -- -c Bad.hs` results in "Irrefutable pattern failed for pattern sel_id : _". Related [GHC bug](https://ghc.haskell.org/trac/ghc/ticket/12788).

    {-# LANGUAGE TemplateHaskell #-}

    module Bad where

    import Data.Aeson.TH
    data Bad = Bad { _bad :: String } deriving (Eq, Ord, Show)
    $(deriveJSON defaultOptions{} ''Bad)

**Comment by jchia** [comment]
I can reproduce the error under Stack LTS-7.5, so this is aeson-0.11.2.1.

**Comment by bergmark** [comment]
This is a GHC panic which means the bug is in GHC. Can you check/file an issue on the GHC tracker?

**Comment by theduke** [comment]
FYI: https://ghc.haskell.org/trac/ghc/ticket/12788

Fixed in 8.0.2

**Comment by bergmark** [comment]
@theduke nice!
