### ISSUE TITLE
[Question] parse blank as null

### ISSUE THREAD

**Issue by isairz** [bos/aeson#490]
Hello, I'm newbie for haskell.

My target json api has odd syntax. This syntax expresses `null` as blank
For example, `[null, null, null]` shows `[,,]`

Can I parse blank as null object using aeson or other library?

**Comment by phadej** [comment]
That's invalid JSON, and `aeson` doesn't try to recover from such parse errors. In fact it's not obvious how to recover from such error. e.g. http://oleg.fi/relaxed-json/ (which I should port to Haskell) parses `[,,]` as `[]`, but could parse as yours `[null, null, null]` or just `[null, null]` (trailing comma!)

**Comment by bergmark** [comment]
Hi @isairz,

I think invalid JSON is out of the scope of this project, I don't want to open pandora's box :)

For your case it sounds like a simple preprocessor could be a fairly straight forward thing to write?

I'll close this as it will not get added to this project, sorry!

**Comment by isairz** [comment]
I agree this case is too strange and to generalize.
As your suggest, it looks good to use preprocessor that replace `,,` to `,null,` and some more.

Thanks for answer!
