### ISSUE TITLE
More general pair

### ISSUE THREAD

**Issue by andrewthad** [bos/aeson#491]
The type signature of pair is:

    pair :: Text -> Encoding -> Series

However, it would make sense to provide another pair function:

    pair' :: Encoding' Text -> Encoding -> Series

This function would be help me improve the performance (very mildly) of something I'm working on.

**Comment by phadej** [comment]
This make sense, please make a PR!

**Comment by andrewthad** [comment]
PR is up https://github.com/bos/aeson/pull/492
