### ISSUE TITLE
ZonedTime fromJSON toJSON

### ISSUE THREAD

**Issue by almays** [bos/aeson#495]
I am befuzzled by `Aeson` and `Servant` conversions of `ZonedTime`.

To my `Servant` app I give some time in the url: `.../2016-12-18T07:51:00+03:00/...`.

`Servant` easily converts it to `ZonedTime` with `... :> Capture "zt" ZonedTime :> ...`.

Then my app does some calculations and in json-response I want to give back to the client this and some other `ZonedTime`s — in case if client wants to give these times to my app again.

If input timezone was not zero `+0X:00` (X /= 0), then on the output I also get `+0X:00`, but if on input I give `.../2016-12-18T07:51:00+00:00/...`,  then in response I get `2016-12-18T07:51:00Z`. And if I try to feed this string to `Servant` again with `.../2016-12-18T07:51:00Z/...`, then `Servant` fails to convert it to `ZonedTime`. Actually is returns `HTTP 400 (Bad Request)`.

Why? What for?

**Comment by phadej** [comment]
Servant's URL param converasion is from http-api-data package

**Comment by bergmark** [comment]
I'm not sure if we can guarantee proper round-tripping for this, but I'm all for that change if someone can verify.

The real problem seems to be that servant is too strict, correct?

**Comment by sopvop** [comment]
Format in [rfc3339 section 5.6](https://tools.ietf.org/html/rfc3339#section-5.6) specifies that offset can be either Z or numeric.
IMO http-api-data should be fixed to parse Z instead of aeson encoding zero offset with "+00:00".

**Comment by bergmark** [comment]
Looks like @phadej already did that https://hackage.haskell.org/package/time-parsers

**Comment by phadej** [comment]
TBH, I didn't benchmarked them, as they are `parsers` not directly `attoparsec` based. But yes, I try to keep them up to date with what is in aeson.

**Comment by almays** [comment]
I also posted it at stackoverflow.
Here is the thread.
http://stackoverflow.com/q/41275758/1726711

Actually, as an issue it can be surely closed.
