### ISSUE TITLE
1.1.0.0 or 1.0.3.0?

### ISSUE THREAD

**Issue by bergmark** [bos/aeson#497]
Apart from #493 the parser now rejects

*  numbers for which the integer portion contains a leading zero.
*  numbers for which a decimal point is not followed by at least one digit,
* documents that contain whitespace outside the set {space, newline, carriage return, tab}.

These changes are subtle and obviously not visible in type signatures, should it be a major bump?

**Comment by phadej** [comment]
I'd say it should. The major bump would communicate "read the changelog" message better. I hope no-one depends on this behaviour, but who knows. People wanted different stuff for numbers in the past too, so someone might accidentally depend on `42.` being parsed. Personally I don't even know what external services send me (they do send weird stuff).
