### ISSUE TITLE
Unexpected UTCTime [de]serialization behaviour

### ISSUE THREAD

**Issue by defanor** [bos/aeson#500]
Here is an example:
```haskell
λ> let t = UTCTime (fromGregorian 2016 12 23) (secondsToDiffTime $ 25 * 3600)
λ> t
2016-12-23 23:59:3660 UTC
λ> encode t
"\"2016-12-23T25:00:00Z\""
λ> eitherDecode (encode t) :: Either String UTCTime
Left "Error in $: could not parse date: Failed reading: invalid time"
```
Though the time is indeed invalid in this case, I'd expect `decode (encode a) == a` to hold. It's rather unfortunate when trying to deserialize aeson-generated JSON with aeson, but even if it is for compatibility with other libraries/languages, perhaps serialization shouldn't produce the values that are considered invalid (even though that may lead to information loss). In any case, it's not quite an expected behaviour: input requirements are more strict than output ones.

**Comment by phadej** [comment]
but you construct invalid `UTCTime`,
utctDayTime :: DiffTime	-- ^ the time from midnight, 0 <= t < 86401s (because of leap-seconds)

Valid options:
- validate hard `UTCTime` invariant, i.e. `error` in this case
- clamp seconds
- don't do anything, use `newtype` for `UTCTime` with broken invariants

I'm not sure which variant is the best one

**Comment by bos** [comment]
I think the current behaviour is quite reasonable. It doesn't prevent someone from deliberately constructing and serializing a bogus `UTCTime`, but that's not the package's job. And it rejects bogus ones. Job done.

**Comment by defanor** [comment]
An invalid UTCTime could be constructed indeliberately (by mistake) as well, in fact that's how I've found it: by parsing it from a format, composition of which turned out to be buggy (while I've assumed that it's not). That was a bug, and now I'm doing basic validation (akin to that in aeson), but was surprising to find it as a deserialization error. Not a big deal though, just writing to explain it better.

**Comment by defanor** [comment]
`fromGregorianValid` checks for leap years, while I doubt that it's viable to check for leap seconds in `mkUTCTimeValid` -- so it still would not be quite consistent (and the time would only be valid just as in "satisfying the given rough invariant"), but it shouldn't harm to open an issue and discuss there as well; I'll do it now.

OOC, why doesn't aeson reuse time's own functions for formatting and parsing? Though neither does it hold in `time` that `parse (print x) == x`, and it manages to violate the invariant anyway (with e.g. 99 seconds), but seems like it should also be fixed there.

**Comment by phadej** [comment]
because we parse `Text` directly, and format/parse different format, we don't need `parseTimeM`/`formatTime` flexiblity (we need different one, actually).
