### ISSUE TITLE
Fold benchmark suites into aeson.cabal

### ISSUE THREAD

**Issue by RyanGlScott** [bos/aeson#504]
Right now, `aeson`'s benchmark suites are sequestered off in a separate `benchmarks` repo, complete with its own `.cabal` file that duplicates much of `aeson.cabal`. This is annoying for several reasons:

1. This `.cabal` file duplicates the amount of work needed to maintain `aeson`, since changes to `aeson.cabal` must be copied over.
2. Furthermore, this upkeep doesn't always happen. Some of the benchmarks seem to be bitrotten (see https://github.com/bos/aeson/pull/335#issuecomment-172730336) or broken (see #502).
3. The benchmarks aren't installable from Hackage or Stackage, which makes them hard to discover. (Plus, if Stackage built the benchmarks regularly, it would help ensure they continue to compile correctly, avoiding scenarios like #502).

We should strive to just copy over the benchmark suites from `aeson-benchmarks.cabal` into `aeson.cabal` to help alleviate these problems.

**Comment by phadej** [comment]
Unfortunately it's not currently possible because of circular dependency (thru `criterion`). This is `Cabal` issue.

**Comment by phadej** [comment]
FWIW: you can give feedback in https://github.com/haskell/cabal/issues/4087

**Comment by bos** [comment]
@RyanGlScott, now you know why this is a common pattern ;-)
