### ISSUE TITLE
Best practices for FromJSON

### ISSUE THREAD

**Issue by andrewthad** [bos/aeson#510]
In the haddocks for `Data.Aeson`, the following example is given:

    {-# LANGUAGE OverloadedStrings #-}
    
    instance FromJSON Person where
        parseJSON (Object v) = Person <$>
                               v .: "name" <*>
                               v .: "age"
        -- A non-Object value is of the wrong type, so fail.
        parseJSON _          = empty

However, this is not the best way to write this instance. In my own code, I would write this:

    {-# LANGUAGE OverloadedStrings #-}
    
    instance FromJSON Person where
        parseJSON = withObject "Person" $ \v -> Person
            <$> v .: "name"
            <*> v .: "age"

This gives better error messages when the JSON is malformed and is more concise. I propose changing the docs to use this as the example.

**Comment by phadej** [comment]
I agree. Using `with*` helpers is much nicer.

**Comment by bergmark** [comment]
I agree!

**Comment by phadej** [comment]
@andrewthad could you make a PR?

**Comment by andrewthad** [comment]
PR is up: https://github.com/bos/aeson/pull/511
