### ISSUE TITLE
aeson-1.1.0.0's test suite fails suddenly

### ISSUE THREAD

**Issue by RyanGlScott** [bos/aeson#514]
If you run:

```
$ cabal get aeson
Unpacking to aeson-1.1.0.0/
$ cd aeson-1.1.0.0/
$ cabal install --enable-tests --only-dependencies
$ cabal configure --enable-tests
$ cabal build
```

And then try to run the tests:

```
$ cabal test --show-details=always
Preprocessing library aeson-1.1.0.0...
Preprocessing test suite 'tests' for aeson-1.1.0.0...
Running 1 test suites...
Test suite tests: RUNNING...
git clone https://github.com/nst/JSONTestSuite tests/JSONTestSuite
Test suite tests: FAIL
Test suite logged to: dist/test/aeson-1.1.0.0-tests.log
0 of 1 test suites (0 of 1 test cases) passed.
```

It fails mysteriously, with only the line `git clone https://github.com/nst/JSONTestSuite tests/JSONTestSuite` as a clue.

Also reproducible in `stack`, as reported in https://github.com/fpco/stackage/issues/2291.

**Comment by bergmark** [comment]
Bryan used git subtree to import the json test suite so the error message is irrelevant. Probably just some missing source files, I'll take a look in a bit.
