### ISSUE TITLE
Documentation of minimal complete definition for `class ToJson` when using non-defaultOptions

### ISSUE THREAD

**Issue by lspitzner** [bos/aeson#518]
(I specified `toEncoding` with special options and discovered that `toJSON` still used defaults.. and now I re-read the docs and I find them unclear:)

The last paragraph reads:

> If DefaultSignatures doesn't give exactly the results you want, you can customize the generic encoding with only a tiny amount of effort, using genericToJSON and genericToEncoding with your preferred Options:
> ~~~~
> instance ToJSON Coord where
>     toJSON     = genericToJSON defaultOptions
>     toEncoding = genericToEncoding defaultOptions
> ~~~~

Should this be s/DefaultSignatures/defaultOptions/ at the start and s/defaultOptions/myFancySpecialOptions/ in the code?

Maybe the "minimal complete definition" can/should be specified clearly for both cases (default and non-default), like it is common in other classes?

**Comment by Lysxia** [comment]
I agree the documentation can be clarified.

> Should this be s/DefaultSignatures/defaultOptions/ at the start and s/defaultOptions/myFancySpecialOptions/ in the code?

I would answer "not quite" to the first, "yes" to the second.

My interpretation is that `DefaultSignatures` refers to the default implementations of the type class methods, though now that you mention it, this isn't worded very well.

By looking at the source of `ToJSON`, you can see that: the default `toJSON` is `genericToJSON defaultOptions`; the default `toEncoding` calls `toJSON`.

https://github.com/bos/aeson/blob/master/Data/Aeson/Types/ToJSON.hs#L274-L296

A minimal complete definition is thus given by `toJSON` (e.g., with `genericToJSON` and custom options). Only redefining `toEncoding` is not sufficient, as you remarked.

**Comment by bergmark** [comment]
Sounds good!

**Comment by bergmark** [comment]
Do you think we are ok to close this now @lspitzner? Please re-open if not.
