### ISSUE TITLE
aeson-1.0.2.1 fails to build with older cabal-installs: "No instance for (Semigroup Builder) arising from a use of `<>'"

### ISSUE THREAD

**Issue by juhp** [bos/aeson#533]
I don't think current aeson builds with some older libraries.

```
Data/Aeson/Encoding/Internal.hs:201:40:
    No instance for (Semigroup Builder) arising from a use of `<>'
    Possible fix: add an instance declaration for (Semigroup Builder)
    In the first argument of `Encoding', namely `(a <> b)'
    In the expression: Encoding (a <> b)
    In an equation for `><':
        (Encoding a) >< (Encoding b) = Encoding (a <> b)

Data/Aeson/Encoding/Internal.hs:220:17:
    No instance for (Semigroup Builder) arising from a use of `<>'
    Possible fix: add an instance declaration for (Semigroup Builder)
    In the second argument of `($)', namely
      `char7 '"'
       <> LT.foldrChunks (\ x xs -> EB.unquoted x <> xs) (char7 '"') t'
    In the expression:
      Encoding
      $ char7 '"'
        <> LT.foldrChunks (\ x xs -> EB.unquoted x <> xs) (char7 '"') t
    In an equation for `lazyText':
        lazyText t
          = Encoding
            $ char7 '"'
              <> LT.foldrChunks (\ x xs -> EB.unquoted x <> xs) (char7 '"') t
Failed to install aeson-1.0.2.1
```
This is with ghc-7.6.3 (from EPEL7).

I am not sure which library is causing this, but would be good to fix the relevant lowerbound.

**Comment by hvr** [comment]
@juhp can you give tell us which versions of the `semigrous`/`bytestring`/`text` packages were used? (if you're using `cabal new-build`, you can look at the `dist-newstyle/cache/plan.json` file)

**Comment by juhp** [comment]
Sure:

ghc-7.6.3
semigroups-0.18.2
bytestring-0.10.8.1

no bytestring-builder installed

**Comment by juhp** [comment]
Guess not: http://matrix.hackage.haskell.org/package/aeson

**Comment by bergmark** [comment]
Can't find the old issue now but are you using an old cabal-install?

**Comment by hvr** [comment]
@juhp ok, I really need more information here as I can't seem to be able to reproduce this even if I force those versions. Can you provide us freeze file as generated by `cabal freeze` or `cabal new-freeze` (or alternatively run `cabal` with a high enough -v setting that emits all used packages & flag settings)?

**Comment by bergmark** [comment]
https://github.com/haskell-infra/hackage-trustees/issues/92 https://github.com/bos/aeson/issues/469

**Comment by hvr** [comment]
Oh wow, totally forgot about that old strange bug. Clearly, we need to accelerate completing `cabal new-build` to make it the default... :-)

**Comment by juhp** [comment]
I see thanks: I am still curious about which of the selected packages are causing the breakage?

```
Dependency attoparsec ==0.13.1.0: using attoparsec-0.13.1.0
Dependency base ==4.6.0.1: using base-4.6.0.1
Dependency base-compat ==0.9.2: using base-compat-0.9.2
Dependency bytestring ==0.10.8.1: using bytestring-0.10.8.1
Dependency containers ==0.5.0.0: using containers-0.5.0.0
Dependency deepseq ==1.3.0.1: using deepseq-1.3.0.1
Dependency dlist ==0.5: using dlist-0.5
Dependency fail ==4.9.0.0: using fail-4.9.0.0
Dependency ghc-prim ==0.3.0.0: using ghc-prim-0.3.0.0
Dependency hashable ==1.2.6.0: using hashable-1.2.6.0
Dependency nats ==1.1.1: using nats-1.1.1
Dependency scientific ==0.3.4.11: using scientific-0.3.4.11
Dependency semigroups ==0.18.2: using semigroups-0.18.2
Dependency tagged ==0.8.5: using tagged-0.8.5
Dependency template-haskell ==2.8.0.0: using template-haskell-2.8.0.0
Dependency text ==1.2.2.1: using text-1.2.2.1
Dependency time ==1.4.0.1: using time-1.4.0.1
Dependency time-locale-compat ==0.1.1.3: using time-locale-compat-0.1.1.3
Dependency transformers ==0.3.0.0: using transformers-0.3.0.0
Dependency transformers-compat ==0.3.3.4: using transformers-compat-0.3.3.4
Dependency unordered-containers ==0.2.8.0: using unordered-containers-0.2.8.0
Dependency uuid-types ==1.0.3: using uuid-types-1.0.3
Dependency vector ==0.10.0.1: using vector-0.10.0.1
Using Cabal-1.16.0 compiled by ghc-7.6
Using compiler: ghc-7.6.3
```
but yeah since this is a user db build I am not so worried.
(I actually filed this before a different issue I see with dlist: I will file that now separately.)

Thanks!

**Comment by juhp** [comment]
(Unfortunately it is quite reproducible with cabal-install-1.16, even after wiping `~/.ghc/`.)

Okay with new-build I managed to get to #534.

**Comment by bergmark** [comment]
It's unfortunate, but I don't know how it could be solved. It's not high prio for me since 1.16 is pretty old and you can upgrade cabal-install without upgrading ghc.

Since this keeps getting reported, even by me :P, I'll keep this open for a while.

**Comment by juhp** [comment]
Feel free to edit the title if it is better to change "ghc/libs" to "cabal-install".
