### ISSUE TITLE
How does constructorTagModifier work during parsing?

### ISSUE THREAD

**Issue by saurabhnanda** [bos/aeson#549]
While it's obvious how the following would be working during encoding:

```
instance ToJSON TxnSource where
  toJSON = genericParseJSON $ (aesonPrefix snakeCase){constructorTagModifier=(camelTo2 '_')}
```

...what is puzzling me is, how can the exact same code work during decoding?

```
instance FromJSON TxnSource where
  parseJSON = genericParseJSON $ (aesonPrefix snakeCase){constructorTagModifier=(camelTo2 '_')}
```

**Comment by phischu** [comment]
In [`parsePair`](https://github.com/bos/aeson/blob/0d742ec32dc5a8f1b02da7dc5a4122611452ffa1/Data/Aeson/Types/FromJSON.hs#L1075) when we decode a constructor we have to compare the tag from the JSON file with the constructor name. We apply the constructor tag modifier to the constructor name before comparison.

**Comment by bergmark** [comment]
@saurabhnanda did that answer your question?

**Comment by saurabhnanda** [comment]
@bergmark yes. Thanks for answering it. I was busy using this technique for my own generic functions 👍
