### ISSUE TITLE
aeson-benchmark-typed broken

### ISSUE THREAD

**Issue by phadej** [bos/aeson#562]
Caused by renaming of the field from `id` to ` id_`.

What's the better way to fix it:
- rename back to `id`
- make `Twitter.Options` with `Options` dealing with that special case? (I prefer this)

Ping @bergmark

**Comment by bergmark** [comment]
I don't remember why the change was made in the first place, but adding `Twitter.Options` sounds good to me!

**Comment by phadej** [comment]
@bergmark tht's what I made in pr #563 (sorry for PR flood, I had few days to spare :)
