### ISSUE TITLE
Overlapping instance of `RecordToPairs` should be incoherent

### ISSUE THREAD

**Issue by Lysxia** [bos/aeson#572]
There is a discrepancy between `FromJSON` and `ToJSON` in the special casing of `Maybe`:

- [`FromJSON` marks the relevant instance `INCOHERENT`](https://github.com/bos/aeson/blob/08fcbcd6ed65d9b3d80300e2bd363bfcd76e38bd/Data/Aeson/Types/FromJSON.hs#L1029) (thanks to #470)

- [`ToJSON` marks the instance `OVERLAPPING`](https://github.com/bos/aeson/blob/08fcbcd6ed65d9b3d80300e2bd363bfcd76e38bd/Data/Aeson/Types/ToJSON.hs#L1012)

This seems to be a bug which has not affected users only thanks to another old bug in GHC, making the instance marked `OVERLAPPING` behave incoherently anyway ([ticket 7296](https://ghc.haskell.org/trac/ghc/ticket/7296), also [ticket 9820](https://ghc.haskell.org/trac/ghc/ticket/9820) for a simpler example).

This bug, if it is indeed one, can be fixed before it gets unmasked: make that `OVERLAPPING` instance `INCOHERENT` instead.

**Comment by Lysxia** [comment]
Here is a snippet demonstrating the problem:

    {-# LANGUAGE DeriveGeneric #-}
    module A where

    import GHC.Generics
    import Data.Aeson
    import Data.Aeson.Types (Parser)

    data F a = F { f :: a } deriving (Show, Generic)

    -- Compiles
    fFromJSON :: FromJSON a => Value -> Parser (F a)
    fFromJSON = genericParseJSON defaultOptions

    -- Overlapping instances error
    fToJSON :: ToJSON a => F a -> Value
    fToJSON = genericToJSON defaultOptions

**Comment by phadej** [comment]
reminds me of https://github.com/bos/aeson/issues/468

I start to think that  the story with "special `Maybe`" is not very coherent... (pun intended).

**Comment by bergmark** [comment]
I don't have any reason to think this difference is intended so fixing it sounds good.

But yeah, incoherent instances are smelly...
