### ISSUE TITLE
Documentation of Option fields disappeared

### ISSUE THREAD

**Issue by Lysxia** [bos/aeson#576]
The fields of `Option`, and thus their individual descriptions, are no longer visible in the docs:

https://hackage.haskell.org/package/aeson-1.2.1.0/docs/Data-Aeson-Types.html#t:Options

It would also be nice to export `Option` and its fields in `Data.Aeson`.

**Comment by phadej** [comment]
`Options` is opaque, so we can add fields without breaking changes.

fields are still visible in https://hackage.haskell.org/package/aeson-1.2.1.0/docs/Data-Aeson-Types.html#v:defaultOptions (hopefully they are up to date).

**Comment by Lysxia** [comment]
How about moving the comments on the fields into the toplevel documentation of `Option`?

Fields are indeed still visible to the compiler, but my second point is that having to import `Data.Aeson.Types` seems unnecessarily inconvenient. `Data.Aeson` already exports `genericToJSON`, but that alone doesn't seem useful, if you can't tweak `defaultOptions`.

**Comment by bergmark** [comment]
Since `defaultOptions` is re-exported already it sounds good to re-export its type as well. I suppose it wouldn't hurt to do the same for the fields incl `SumEncoding`. Does re-exporting them fix the documentation issues?
