### ISSUE TITLE
"Inconsistent" ToJSON/FromJSON instances for Either

### ISSUE THREAD

**Issue by saurabhnanda** [bos/aeson#590]
Any reason why the pre-defined ToJSON/FromJSON instances of Either are very different from the rest of the default/generic machinery. To elaborate:

```
data MyEither a b = MyLeft a | MyRight b deriving (Eq, Show, Generic, FromJSON, ToJSON)
putStrLn $ toS $ encode (MyLeft 10 :: MyEither Int String)
-- {"tag":"MyLeft","contents":10}
```

vs

```
putStrLn $ toS $ encode (Left 10 :: Either Int String)
-- {"Left":10}
```

What is the recommended way to "opt-in" to pre-defined ToJSON/FromJSON instances? eg. I'd like to use every other pre-defined JSON instance _except_ Either. From how the [code is structured](https://www.stackage.org/haddock/lts-9.0/aeson-1.1.2.0/src/Data.Aeson.Types.ToJSON.html) I don't think I can import the class definitions and instance definitions separately. Would you be open to a PR to make this possible? This would also require the modules to be exposed to the outside world and not remain hidden.

**Comment by saurabhnanda** [comment]
A practical problem this behaviour is posing: we're auto-generating JSON parsers in Typescript and were assuming a standard way in which sum types would be encoded, i.e. using `defaultTaggedObject`. We have ensured that all our custom sum-types are encoded consistently via `defaultTaggedObject`, but suddenly `Either` is encoded in a completely different manner.

**Comment by saurabhnanda** [comment]
It seems that [Purescript's argonaut library](https://github.com/purescript-contrib/purescript-argonaut-codecs/blob/2fbd8e84f2944fd8a6d9d021d5e0abe4a803616f/src/Data/Argonaut/Encode/Class.purs#L25-L31) also defaults to using some kind of tagged object. I wonder how Haskell<>Purescript bridge libraries would be dealing with this inconsistency.

**Comment by bergmark** [comment]
aeson used to contain more orphans internally (for other reasons), it messed up haddocks so we decided to remove them.

Remember that instance imports are transitive so depending on an orphan not being imported is very fragile, if you were to use some other package that mentions the Either instance you would be back were you started.

One option is to use a fork of aeson with the instances removed. If you use CPP to filter it out it should be pretty straight forward to maintain it. This suffers from the opposite problem of orphans, you won't be able to compile any other dependencies that need this instance.

Another option is to define your own type classes that mirror aeson's, then you get to opt-in to instances instead. I recommend trying this first. It can work depending on how flexible other libraries you need to use with these type classes are (e.g. if you can add a new type class for serialization to your web server)

> It seems that Purescript's argonaut library also defaults to using some kind of tagged object.

Note that argonaut is still not consistent wrt sum types as `Maybe` still has a special format.

> I wonder how Haskell<>Purescript bridge libraries would be dealing with this inconsistency.

From my limited experience with [purescript-bridge](https://hackage.haskell.org/package/purescript-bridge) I think you can override instances locally for one bridge.

HTH

**Comment by bergmark** [comment]
Another option is to make sure `Either` is not part of the default imports of your json modules, that way you at least have to jump through some hoops to use it by accident.

I'll close this for now, but we can re-open if there's anything else to discuss.
