### ISSUE TITLE
Run hlint on travis using precompiled binary

### ISSUE THREAD

**Issue by bergmark** [bos/aeson#598]
This should speed up that build step quite a bit, instructions for using the binary are available here https://github.com/ndmitchell/hlint#running-with-continuous-integration but note that i'd still like it to be run with `make lint` (or in some other way that doesn't add duplication) since we need to pass along a bunch of options.

**Comment by phadej** [comment]
We can get binary from: https://github.com/ndmitchell/hlint/releases/download/v2.0.9/hlint-2.0.9-x86_64-linux.tar.gz

**Comment by wisn** [comment]
Is there a Docker image for HLint?

**Comment by bergmark** [comment]
Not that I know of, but isn't docker a bit overkill for this when we have compatible binaries available?

**Comment by wisn** [comment]
Well yeah it is overkill
