### ISSUE TITLE
How to best handle uppercase JSON variables?

### ISSUE THREAD

**Issue by rszibele** [bos/aeson#601]
What's a good way to handle uppercase variables in aeson?

Suppose I have this JSON object:
```
{
    "X": 123.4,
    "Y": 567.8
}
```

I can't just do the following because it wont compile:
```
data Coordinate = Coordinate {
      X :: Double
    , Y :: Double
} deriving (Generic, ToJSON, FromJSON)
```

Will I have to manually re-map the variables or is there a better way of doing this, for example a hash map or something else?

**Comment by phadej** [comment]
Use 

```haskell
instance ToJSON Person where
    toEncoding = genericToJSON defaultOptions
        {  fieldLabelModifier = map toUpper }
```

See e.g. http://hackage.haskell.org/package/aeson-1.2.3.0/docs/Data-Aeson.html#t:FromJSON (look for `customOptions`

**Comment by rszibele** [comment]
Thanks!
