### ISSUE TITLE
Allow trailing commas?

### ISSUE THREAD

**Issue by jeffersoncarpenter** [bos/aeson#603]
Is there a way to allow trailing commas in JSON arrays and objects when parsing or encoding?  Trailing commas do not conform to the JSON spec, but some (myself included) overwhelmingly prefer the uniformity.  If aeson does not allow this, then I would be interested in either modifying aeson to provide this option, or maintaining my own JSON parser, if you would not be interested in merging in such a change.

Have a good day, all!

**Comment by bergmark** [comment]
Hi @jeffersoncarpenter,

Unfortunately I think extensions to JSON itself is out of scope of aeson.

I think the better option is to have a separate library that can repair invalid JSON and produce a `ByteString` or `Value` which can then be passed along to aeson so you won't have to re-implement the type class machinery. This use case wouldn't be optimal performance-wise, but it would keep the aeson code base simpler by tailoring it to just JSON.
