### ISSUE TITLE
Compiling aeson-benchmark-dates with GHC 7.8 and 7.10 exhausts simplifier ticks

### ISSUE THREAD

**Issue by Lysxia** [bos/aeson#606]
Like #502, but different GHC versions. Perhaps there is another `INLINE` to kill somewhere.

**Comment by Lysxia** [comment]
```
[1 of 1] Compiling Main             ( Dates.hs, .stack-work-bench/dist/x86_64-linux-nopie/Cabal-1.18.1.5/build/aeson-benchmark-dates/aeson-benchmark-dates-tmp/Main.o )
ghc: panic! (the 'impossible' happened)
  (GHC version 7.8.4 for x86_64-unknown-linux):
	Simplifier ticks exhausted
    When trying RuleFired unpack
    To increase the limit, use -fsimpl-tick-factor=N (default 100)
    If you need to do this, let GHC HQ know, and what factor you needed
    To see detailed counts use -ddump-simpl-stats
    Total ticks: 0
```

**Comment by Lysxia** [comment]
This seems to be the culprit, `{-# OPTIONS_GHC -fsimpl-tick-factor=0 #-}` at the top of `Dates.hs`.

https://github.com/bos/aeson/commit/a1044ddf60dff9826ccd21f50c7457b73e5996b8#diff-9bba089938d5c25fc49447099a94decc

**Comment by bergmark** [comment]
@phadej do you remember the reason you added that line?

**Comment by phadej** [comment]
@bergmark I don't remember, most likely it was my mistake (for some limits, setting to 0 is as setting to infinity).
