### ISSUE TITLE
Alternative instance on `Either String`

### ISSUE THREAD

**Issue by KtorZ** [bos/aeson#609]
Hi guys, this is not an issue per se but more like a mystery I am trying to solve. Recently, I wrote instinctively without really thinking about it something like this:

```hs
 Aeson.eitherDecodeStrict' bytes <|> Yaml.decodeEither bytes
```

This compiles fine with GHC and is kinda intuitive if we imagine that `Either String` is actually an alternative with `Left ""` as an identity (or `Left "mzero"` like the `Result` type in aeson). However, neither Control.Applicative nor Data.Either define such instances. 

If you try something like the line below in a "raw" ghci repl, you get what you would expect looking at the way `Either` and `Alternative` are define in `base`.

```hs
$> (Left "" :: Either String Int) <|> (Right 14 :: Either String Int)
-- No instance for (Alternative (Either String)) arising from a use of ‘<|>’
```

However, if one simply imports `Data.Aeson`, the same line actually works fine. 

```hs
$> (Left "" :: Either String Int) <|> (Right 14 :: Either String Int)
Right 14
```

My first clue was that `aeson`, somewhere, defines an orphan instance for `Either String` or `Either e` when `e` has an identity... but, I couldn't find anything. Weird enough, should you try the same thing with `Either Text` (with Data.Aeson imported), you get GHC looking for a `Control.Monad.Trans.Error.Error Text` (from the `transformers` package) instance instead of a `Alternative (Either Text)` instance.

Any clue ?

**Comment by phadej** [comment]
See https://ghc.haskell.org/trac/ghc/ticket/9588

**Comment by KtorZ** [comment]
So this comes from the orphan instances in `transformers`. Thanks :+1:

**Comment by bergmark** [comment]
You can figure this out using GHCi:
```
Prelude Data.Aeson Control.Applicative> :i Alternative
class Applicative f => Alternative (f :: * -> *) where
  empty :: f a
  (<|>) :: f a -> f a -> f a
  some :: f a -> f [a]
  many :: f a -> f [a]
  {-# MINIMAL empty, (<|>) #-}
  	-- Defined in ‘GHC.Base’
instance Alternative Result
  -- Defined in ‘aeson-1.2.3.0:Data.Aeson.Types.Internal’
instance GHC.Base.MonadPlus m => Alternative (WrappedMonad m)
  -- Defined in ‘Control.Applicative’
instance (Control.Arrow.ArrowZero a, Control.Arrow.ArrowPlus a) =>
         Alternative (WrappedArrow a b)
  -- Defined in ‘Control.Applicative’
instance [safe] Control.Monad.Trans.Error.Error e =>
                Alternative (Either e)
  -- Defined in ‘Control.Monad.Trans.Error’
instance Alternative [] -- Defined in ‘GHC.Base’
instance Alternative Maybe -- Defined in ‘GHC.Base’
instance Alternative IO -- Defined in ‘GHC.Base’
```
