### ISSUE TITLE
docs of Data.Aeson.Text.encodeToTextBuilder mention "encodeToBuilder"

### ISSUE THREAD

**Issue by lspitzner** [bos/aeson#612]
but that does not seem to exist/be exposed (since 1.*)

i suppose that function would be `encodingToLazyByteString . toEncoding` ?

**Comment by phadej** [comment]
It's in http://hackage.haskell.org/package/aeson-1.2.3.0/docs/Data-Aeson-Text.html

**Comment by phadej** [comment]
(If you really want to get `Data.Text.Lazy.Builder`, not the `ByteString` one.)

**Comment by lspitzner** [comment]
> It's in http://hackage.haskell.org/package/aeson-1.2.3.0/docs/Data-Aeson-Text.html

what is? `Data.Aeson.Text.encodeToTextBuilder`? well, obviously? did you misread?
(i do want a ByteString (builder).)

**Comment by phadej** [comment]
Yes, I missread. 

Then it's `fromEncoding . toEncoding` , http://hackage.haskell.org/package/aeson-1.2.3.0/docs/Data-Aeson-Encoding.html#v:fromEncoding

**Comment by phadej** [comment]
naming is little confusing, blame me for that (unsafeFromBuilder & toBuilder could be better...)
