### ISSUE TITLE
GSoC 2018 Ideas for Haskell.org

### ISSUE THREAD

**Issue by wisn** [bos/aeson#616]
Google Summer of Code will take place again in 2018. Last year, Haskell.org was not selected, and we decided to run our own program, which ended very successfully.

Currently, we are in the process of gathering ideas for the students. I think it would be great to have an Aeson project in there. Projects should be concrete and small enough in scope such that they can be finished by a student in three months. Mind to discussing the idea here? Or, just send the idea to HSoC [repository](https://github.com/haskell-org/summer-of-haskell/).

For context, Google Summer of Code is a program where Google sponsors students to work on open-source projects during the summer. Haskell.org has taken part in this program from 2006 until 2015. Many important improvements to the ecosystem have been the direct or indirect result of Google Summer of Code projects, and it has also connected new people with the existing community.

Reference: <https://summer.haskell.org/news/2017-12-25-call-for-ideas.html>
Current Ideas: <https://summer.haskell.org/ideas.html>
Repository: <https://github.com/haskell-org/summer-of-haskell/>

**Comment by bergmark** [comment]
Thanks for the heads up!

The thing that comes to mind is the work we have started on accumulating multiple parsing failures over at #597. With a guesstimate it could be a good size for a GSoC.

I can go through the open issues later and see if there are other good sized projects in there.

I'd also appreciate hearing ideas from others.

**Comment by wisn** [comment]
You guys may discuss till 18th then choose several ideas to be submitted to HSoC repository. The timeline is available [here](https://developers.google.com/open-source/gsoc/timeline). Don't forget that each idea need a mentor. I will be back on 16th.
