### ISSUE TITLE
ToJSON/FromJSON instances fail for UTCTime, DiffTime

### ISSUE THREAD

**Issue by brainwave0** [bos/aeson#622]
If I try to make an instance for a custom type that includes a UTCTime or a DiffTime, I get a compile error. For example, if I try to compile the folowing code

    {-# LANGUAGE DeriveGeneric #-}
    import GHC.Generics
    import Data.Aeson
    import Data.Time
    data Foo = Foo UTCTime deriving (Generic, Show)
    instance ToJSON Foo
    instance FromJSON Foo

I get

    /home/ian/test.hs:6:10:
        No instance for (ToJSON UTCTime)
          arising from a use of ‘aeson-1.2.4.0:Data.Aeson.Types.ToJSON.$gdmtoJSON’
        In the expression: aeson-1.2.4.0:Data.Aeson.Types.ToJSON.$gdmtoJSON
        In an equation for ‘toJSON’:
            toJSON = aeson-1.2.4.0:Data.Aeson.Types.ToJSON.$gdmtoJSON
        In the instance declaration for ‘ToJSON Foo’
    
    /home/ian/test.hs:7:10:
        No instance for (FromJSON UTCTime)
          arising from a use of ‘aeson-1.2.4.0:Data.Aeson.Types.FromJSON.$gdmparseJSON’
        In the expression:
          aeson-1.2.4.0:Data.Aeson.Types.FromJSON.$gdmparseJSON
        In an equation for ‘parseJSON’:
            parseJSON = aeson-1.2.4.0:Data.Aeson.Types.FromJSON.$gdmparseJSON
        In the instance declaration for ‘FromJSON Foo’

**Comment by bergmark** [comment]
I'm not able to reproduce this. It could be because aeson is compiled against a different version of time than what is used in your module. Are you using cabal-install? Did you get a warning about multiple versions at any point? I thought these kind of issues didn't occur anymore so it could be something else going wrong.

**Comment by brainwave0** [comment]
I did update time to the latest version. Could that be it?

**Comment by bergmark** [comment]
Could be, time ships with GHC so it's inadvisable to upgrade it as you easily get into conflicts that way. But build tools will usually prevent you from doing it unless you use e.g. `--force-reinstalls`
