### ISSUE TITLE
Export something similar to Yaml's encodeFile/decodeFile

### ISSUE THREAD

**Issue by Pastafarianist** [bos/aeson#623]
`yaml` has two handy helpers called [`encodeFile`](https://hackage.haskell.org/package/yaml-0.8.2/docs/Data-Yaml.html#v:encodeFile) and [`decodeFile`](https://hackage.haskell.org/package/yaml-0.8.2/docs/Data-Yaml.html#v:decodeFile). It would be convenient if `aeson` exported something similar as well.

**Comment by phadej** [comment]
If someone makes a PR, please use `strict` variants of `encode` / `decode` :)

**Comment by bergmark** [comment]
What is the preferred way to do this nowadays, is using base good? or good enough?

**Comment by bergmark** [comment]
#625
