### ISSUE TITLE
Genericly derived FromJSON instance incorrectly reports structural error 

### ISSUE THREAD

**Issue by JustusAdam** [bos/aeson#627]
The following code *should* in my opinion work.

However the output is not `success` but this:

```
"0"
Error in $: expected Int, encountered Object
```

### Code for the example:

```hs
import Data.Aeson
import GHC.Generics

newtype MyType = MyType Int deriving (Eq, Show, Generic)


baseOptions :: Options
baseOptions =
    defaultOptions
        {unwrapUnaryRecords = True, fieldLabelModifier = camelTo2 '_'}


instance ToJSON MyType where
    toJSON = genericToJSON baseOptions
    toEncoding = genericToEncoding baseOptions

instance FromJSON MyType where
    parseJSON = genericParseJSON baseOptions


main =
    let example = MyType 0
        asJSON = encode example
     in do print asJSON
           case eitherDecode asJSON of
               Left err -> putStrLn err
               Right v
                   | v == example -> putStrLn "success"
                   | otherwise -> print v
```

### A little more explanation

I started to encounter this, if not erroneous, unintuitive behaviour after I removed the fields from some newtypes. Meaning before I had structures like these:

```hs
newtype MyType = MyType { unwrapMyType :: Int } deriving (Eq, Show, Generic)
```

They had the same instances for `ToJSON` and `FromJSON` with the same options, the only things I changed was removing the accessor for the field. Furthermore they were compiled with the same `aeson` version. 

Also adding an accessor back into the newtype declaration makes it run as expected again!

Observed with `aeson` version `1.2.3.0`

**Comment by bergmark** [comment]
So there is a mismatch between derivation of To/FromJSON instances with newtypes? That should definitely be fixed. But the error message seems strange too, why does it say that it encountered an Object?

But a workaround, and what I would recommend for newtypes is using GeneralizedNewtypeDeriving:

```haskell
newtype MyType = MyType Int deriving (Generic, FromJSON, ToJSON)
```

**Comment by Lysxia** [comment]
I think `aeson` should imitate newtype-deriving by default for newtypes precisely because of this kind of scenario, possibly with yet another option to disable it for people who want the record-like behavior.

**Comment by JustusAdam** [comment]
@bergmark actually the `newtype` is not the problem. After reading your comment I tried the example with `data` instead and it exhibits the same behaviour. 
I think it may have possibly something to do with how `unwrapUnaryRecords` is interpreted in the face of a non-record data type. 

Whats strange in my eyes is 

1. Whereas `toJSON`/`toEncoding` unwraps the constructor (which is what I wanted) `fromJSON` does not parse the same representation back.
2. The error message makes no sense. Actually the error message suggest that it does the *right* thing (which is to expect an int) however claims to encounter an object, which we know is wrong as there is no object anywhere.

**Comment by Lysxia** [comment]
The bug is in `FromJSON`, in the bit that decides how to handle a constructor. When `unwrapUnaryRecords` is on and the constructor is unary, the `Value` gets wrapped into a dummy `Object` so that the rest of the parser can handle it as if it were an actual record. However this is done regardless of whether the constructor is actually a record, and when it is not, the rest of the parser is not expecting that wrapper record. This explains the error message.

https://github.com/bos/aeson/blob/e3dbf903980c26839713728ff80996bf126851bc/Data/Aeson/Types/FromJSON.hs#L1004
