### ISSUE TITLE
Suggestion: Remove all the benchmark numbers from the package description

### ISSUE THREAD

**Issue by ocharles** [bos/aeson#628]
`aeson` is the de facto standard for JSON parsing, so I don't think we need to argue the case based on benchmark numbers. I suggest this, because on landing on https://hackage.haskell.org/package/aeson-1.3.0.0, I don't think we want to show any information that users aren't actively seeking.

**Comment by bergmark** [comment]
Agreed and removed, these numbers are old anyway.
