### ISSUE TITLE
Improve error reporting for withObject and other with* functions

### ISSUE THREAD

**Issue by Lysxia** [bos/aeson#632]
I started working on #474 and ended up refactoring a whole bunch of `FromJSON` (again), and there is one bit about error reporting I'd like to ask about.

Currently `withObject` just passes the `expected` string to `typeMismatch`, so we see error messages looking like:

    > withObject "MyType" (\obj -> (...)) (String wtf)
    expected MyType, encountered String

Wouldn't it be more helpful to remember that we are trying to parse a JSON object? I think this would look better:

    when parsing MyType, expected Object, encountered String

Using the following alternative implementation of the error clause of `withObject` ([current version](https://github.com/bos/aeson/blob/2090406efe649ec86b9b279c9ee7ddc53b01381c/Data/Aeson/Types/FromJSON.hs#L632)):

    ...
    withObject context _ v =
        modifyFailure (\e -> "when parsing " ++ context ++ ", " ++ e)
          (typeMismatch "Object" v)

Does that look reasonable?

It's worth mentioning that that implementation is not equivalent to applying `modifyFailure` outside of the current `withObject`:

    modifyFailure (\e -> "when parsing " ++ context ++ ", " ++ e) . withObject "Object" (...)

which would modify the failure message even if the value is an object (as expected) but a failure occurs later in the continuation. The proposed version above only modifies the failure to unwrap the object, and forgets about the `context` string otherwise.

This change only affects error messages, is it fine to simply change `withObject` (and other `with*` functions), or should we give the new version a different name?

How are the contents of error messages considered for the purposes of versioning?

More generally, I also propose to change the documented usage of `typeMismatch`. Instead of the current usage of applying it to the current Haskell type we are parsing ([such as `"Coord"` in the current doc](https://github.com/bos/aeson/blob/2090406efe649ec86b9b279c9ee7ddc53b01381c/Data/Aeson/Types/FromJSON.hs#L499)), I would recommend to applying it to the actually expected JSON type as its first argument, and to provide any additional context (such as `"Coord"`) via `modifyFailure`, or possibly a new `prependFailure` combinator to avoid the lambda or awkward operator section (which must be written `((x ++ y) ++)`) and not `(x ++ y ++)`).

**Comment by bergmark** [comment]
> Wouldn't it be more helpful to remember that we are trying to parse a JSON object? I think this would look better: when parsing MyType, expected Object, encountered String

Agreed!

>  is it fine to simply change withObject (and other with* functions), or should we give the new version a different name?

I think it's fine to change them, I don't think anyone minds accidentally getting better error messages :-) It may make sense to be stricter about it wrt versioning at some point, but since we mostly don't have tests for errors they may change by accident anyway... For now my recommendation for anyone who cares about specific error messages is to have their own regression tests.

The changes to the typeMismatch docs sound good too!

**Comment by neongreen** [comment]
> which would modify the failure message even if the value is an object (as expected) but a failure occurs later in the continuation. The proposed version above only modifies the failure to unwrap the object, and forgets about the context string otherwise.

I really wish the behavior was actually "modify the failure message even if the value is an object (as expected) but a failure occurs later in the continuation" :slightly_smiling_face:
