### ISSUE TITLE
Golden testing for error messages

### ISSUE THREAD

**Issue by Lysxia** [bos/aeson#633]
As I'm working on aeson's error reporting features, I wonder how to test them and prevent regressions. [Golden testing](https://ro-che.info/articles/2017-12-04-golden-tests) seems like the most promising approach. For example here's a file testing the various error paths from the `Generic` implementation of  `FromJSON`, and the corresponding output (from a branch I'm working on):

https://gist.github.com/Lysxia/1973dfd188dd4ff84c34dd636a90d781

It would be quite tedious to set up and maintain this in [the current unit-test style](https://github.com/bos/aeson/blob/master/tests/UnitTests.hs#L260-L275), of interleaving the expected output in the source code.

- Are there better alternatives than unit or golden testing for error messages?

- Is there already a golden testing library compatible with test-framework or HUnit (that aeson is already using)? If not, I'm hesitating between creating a new one or using tasty-golden. Should we avoid depending on another test framework?

**Comment by Lysxia** [comment]
- Is there a problem with switching to tasty (which has tasty-golden)?

**Comment by phadej** [comment]
I'm not a maintainer, but I don't see problems with `tasty`.

**Comment by bergmark** [comment]
I wouldn't mind switching to tasty! Sounds like the best out of these alternatives, I'm not aware of any other solutions.
