### ISSUE TITLE
Missing function in documentation

### ISSUE THREAD

**Issue by centromere** [bos/aeson#638]
In the documentation for [encodeToTextBuilder](https://www.stackage.org/haddock/lts-11.7/aeson-1.2.4.0/Data-Aeson-Text.html#v:encodeToTextBuilder) it states,

> If you are going to immediately encode straight to a `ByteString`, it is more efficient to use `encodeToBuilder` instead.

I am unable to locate `encodeToBuilder` anywhere.

**Comment by bergmark** [comment]
Thanks, it seems like this was fixed in a later release, compare with https://hackage.haskell.org/package/aeson-1.3.1.1/docs/Data-Aeson-Text.html
