### ISSUE TITLE
Unexpose gparseJson

### ISSUE THREAD

**Issue by bergmark** [bos/aeson#655]
in #653 @Lysxia said

> It's unfortunate that gParseJSON is exported in the toplevel modules Data.Aeson/Data.Aeson.Types. Users should really not depend on these Generics internals. It would be a good idea to hide this at some point [..] so we can just remove gParseJSON.

We should at least wait for #653 to be merged, then we can also rename the new `gparseJson'` to `gparseJson` at the same time. But I'd also like to avoid doing a major release since we had one recently and this change is mostly hygienic. 

I wonder if anyone is using the current `gparseJson`? If they are they would probably like to use `gparseJson'` instead. Some investigation on aeson usages on hackage/stackage would be nice.

**Comment by Lysxia** [comment]
Github-searching for `gParseJSON` returns 230 or so results, and almost all occurences are either `gparseJSON` from `generic-aeson` (that could be filtered out if Github search were case-sensitive) or in duplicates of the `FromJSON` module, so it was quick to go through all of them.

The only two actual matches are [one inactive repo (unreleased)](https://github.com/rvion/ride/blob/655003916da9629b96e537ae809053e6d2e406b6/jetpack/src/Data/Aeson/AsJs.hs) that just reexports it without using it, and [a more active one](https://github.com/cuauv/software/blob/8e3b7599b11a41bc016025e116fd22ee861918ec/aslam/deprecated/v4/src/Utility/Serialization.hs) that could certainly do without it (and that file is located under a directory named `deprecated/`...).

**Comment by phadej** [comment]
Let's do this for 1.5
