### ISSUE TITLE
FromJSONKeyCoerce warning

### ISSUE THREAD

**Issue by MaxGabriel** [bos/aeson#659]
Hi, I just installed aeson-1.4.0.0 and got this warning:

```
Data/Aeson/Types/FromJSON.hs:468:3: warning: [-Winline-rule-shadowing]
    Rule "FromJSONKeyCoerce: fmap id" may never fire
      because ‘id’ might inline first
    Probable fix: add an INLINE[n] or NOINLINE[n] pragma for ‘id’
    |
468 |   "FromJSONKeyCoerce: fmap id"     forall (x :: FromJSONKeyFunction a).
    |
```

It's not causing me any problems, just wanted to let you know.

Looks like the warning may have been around awhile since it appears here as well: https://github.com/bos/aeson/issues/543

**Comment by bergmark** [comment]
Thanks,

I'm not sure if id will always inline first or not? If it does we might as well remove the rule, but otoh it shouldn't hurt to keep it. We would want to keep the rule if it triggers sometimes, if so we could just disable the warning. I'm sure  there is a reason `id` isn't marked with (NO)INLINE.
