### ISSUE TITLE
Instances for Void/V1?

### ISSUE THREAD

**Issue by wyager** [bos/aeson#661]
Would this be OK?

```haskell
instance GFromJSON arity V1 where gParseJSON _ _ _ = fail "Attempted to parse empty type"
instance GToJSON Value arity V1 where gToJSON _ _ x = case x of {}
```

The specific use case here is `Servant.API.WebSocketConduit` - I want to specify an API with no input values.

**Comment by bergmark** [comment]
Are there side effects if this change is made? I remember avoiding this instance in generic-aeson but I can't remember why... I also remember we defined To/FromJSON Void instances in rest-types with the same motivation as you.

**Comment by wyager** [comment]
> Are there side effects if this change is made? 

Can't think of any (negative) side effects. Did you have any sort of thing in mind?

**Comment by bergmark** [comment]
Nah I can't think of any problems with it either so I'm fine with adding it!

**Comment by wyager** [comment]
https://github.com/bos/aeson/pull/663
