### ISSUE TITLE
JSON instance for path

### ISSUE THREAD

**Issue by 2mol** [bos/aeson#677]
Hi everybody!

I want to ask if people would be open to shipping `aeson` with a JSON instance for [`path`](https://hackage.haskell.org/package/path)

Currently, that instance is provided by path itself, which makes it inherit the entire dependency graph of`aeson.

If aeson depended on path instead, it would gain two new transitive dependencies instead: `exceptions` and `filepath`. I think path is common and high-quality enough for that to be an ok tradeoff. Since `Data.Aeson.Types` includes a lot of very useful instances already, it feels like an elegant solution to include one for path as well.

How do aeson maintainers feel about this?

Or maybe there is a more elegant solution? Feel very welcome to chime in on the discussion on path's side as well: https://github.com/commercialhaskell/path/issues/136

**Comment by hvr** [comment]
While `path` is popular it isn't the canonical choice for representing paths in a typesafe(r) way. The design space is huge, and `path` picked one specific corner. And aeson shouldn't get in the business of endorsing one competitor over the other, nor can `aeson` be expected to start adding instances for all packages providing a path abstraction. Hence I don't consider this a good idea.

**Comment by 2mol** [comment]
Ok, fair enough. Thanks for weighing in so quickly though!
