### ISSUE TITLE
Not in scope: type constructor or class ‘ToJson’

### ISSUE THREAD

**Issue by dividedbynil** [bos/aeson#682]
This happens in aeson 1.3.1.1, I've imported Data.Aeson, but the error still occur.

**Comment by Lysxia** [comment]
It's `ToJSON` with the latter parts in all caps.

**Comment by dividedbynil** [comment]
> It's `ToJSON` with the latter parts in all caps.

You're right, it's my fault! Thanks for pointing it out.
