### ISSUE TITLE
Should Value have a Monoid instance?

### ISSUE THREAD

**Issue by JustinChristensen** [bos/aeson#686]
`Null` could be seen as an identity value with respect to OR:

```haskell
mempty `mappend` String "foo" == String "foo"
String "foo" `mappend` mempty == String "foo"
```

**Comment by Lysxia** [comment]
What does it mean to `mappend` a `Number` and an `Object`? A `Number` and a `Bool`?

**Comment by JustinChristensen** [comment]
I suppose `mappend` would have to be implemented according to the Javascript notion of truthiness:

```javascript
null || false
// false
33 || true
// 33
"foo" || {}
// "foo"
x = {}
x || []
// {}
```

**Comment by llelf** [comment]
No.
- this makes zero sense;
- *OR* opertion has nothing to do with it;
- javascript has nothing to do with it

**Comment by JustinChristensen** [comment]
@llelf If others feel that way, I'm satisfied. Issue can be closed.

**Comment by JustinChristensen** [comment]
```haskell
instance Monoid Value where
    mempty = Null

    mappend Null y = y
    mappend x _ = x
```

**Comment by JustinChristensen** [comment]
For my use-case I really just need `mempty`. If the above `Monoid` definition doesn't seem useful, how about adding a `Default` instance for Value? I can open the PR.

**Comment by phadej** [comment]
`Default` it oo controversial. Why can't you simply say `Null`?

**Comment by JustinChristensen** [comment]
@phadej I decided to go a different route for my thing, and now I don't need to use `Value` or any new `Value` instances. It also sounds like adding an instance of `Monoid` or `Default` wouldn't be very useful, and so I'm closing this.
