### ISSUE TITLE
omitNothingFields does not work with Maybe from type parameter

### ISSUE THREAD

**Issue by htmue** [bos/aeson#690]
Maybe-fields are always required if the field's type is introduced by type parameter. Example:
```haskell
> data G a = G { a :: a, b :: Maybe Int } deriving (Show, Generic)
> instance FromJSON a => FromJSON (G a) where parseJSON = genericParseJSON defaultOptions {omitNothingFields=True}
> eitherDecode "{}" :: Either String (G (Maybe Int))
Left "Error in $: key \"a\" not present"
```
When the key is missing and `omitNothingFields = True`, parsing should succeed, as it does for `b`:
```haskell
> eitherDecode "{\"a\": null}" :: Either String (G (Maybe Int))
Right (G {a = Nothing, b = Nothing})
```

**Comment by Lysxia** [comment]
One way is to specialize the variable `a` in the instance declaration:

    instance FromJSON b => FromJSON (G (Maybe b)) where
      parseJSON = genericParseJSON defaultOptions {omitNothingFields=True}

You'll have to deal with overlapping instances if you also want other instantiations of `G`.

> When the key is missing and `omitNothingFields = True`, parsing should succeed

There is a fundamental limitation in the way type classes work that makes this infeasible. The implementation of the `omitNothingFields` option is quite fragile (and my above suggestion abuses that). Properly supporting this use case would require a significant redesign of aeson's generic machinery.

**Comment by htmue** [comment]
That's a clear answer, thanks a lot!

Your suggestion works well for my toy example, but in the complex context where I actually need it, I get link errors (symbol missing). I guess that's due to the fragility you mention.

I found a simple solution though - inserting `"a": null` if the optional key is missing.
```haskell
instance FromJSON a => FromJSON (G a) where
  parseJSON =
    genericParseJSON defaultOptions {omitNothingFields = True} . fixOptionalKey "a"

fixOptionalKey :: Text -> Value -> Value
fixOptionalKey key (Object o) = Object $ H.insertWith (flip const) key Null o
fixOptionalKey _ v = v
```

**Comment by Lysxia** [comment]
Link errors sound like an unrelated problem. But I'm glad you found a solution!

**Comment by htmue** [comment]
Me too.

However, I think it would be good to document this behaviour, it's unexpected and needs a workaround.

I came across this while trying to make the [haskell-lsp RequestMessage](https://github.com/alanz/haskell-lsp/blob/master/haskell-lsp-types/src/Language/Haskell/LSP/Types/Message.hs#L268) conform to the spec (`"params": null` may be omitted), so that haskell-ide-engine shutdown works properly with Sublime LSP.

Here also the link error happens with the overlapping instances solution (GHC 8.6.3/8.6.4 on the Mac), if and only if the second instance is present. The libraries build without warnings or errors and the code works in ghci, but linking is impossible.

I don't know if this is related to aeson or not. If you like to investigate further, I could provide the code.
