### ISSUE TITLE
Doesn't parse escaped double quotes correctly

### ISSUE THREAD

**Issue by thomasjm** [bos/aeson#692]
Aeson doesn't seem to decode escaped double quotes correctly. Consider a simple JSON string containing quotes, like `"print(\"hi\")"`. If we try to decode it as a string, we get an error:

```
> import qualified Data.Aeson as A
> import Data.String.Interpolate.IsString
> :set -XQuasiQuotes
> A.eitherDecode [i|"print(\"hi\")"|] :: Either String String
Left "Error in $: endOfInput"
```

AFAICT this is valid JSON, so this seems like a nasty bug.

I first noticed this when trying to decode lists of strings, i.e.

```
> A.eitherDecode [i|["abc", "print(\"hi\")"]|] :: Either String [String]
Left "Error in $: Failed reading: satisfy"
```

**Comment by llelf** [comment]
It's `interpolate` that is broken, not `aeson`.

```hs
λ> A.eitherDecode @Value "\"print(\\\"hi\\\")\""
Right (String "print(\"hi\")")
```

**Comment by thomasjm** [comment]
Aah you're right, my real issue was something different and I tried to debug by pasting it into `interpolate`, so this was a red herring. I'll look into filing an issue on `interpolate`.

Thanks and sorry for the spam!

**Comment by thomasjm** [comment]
For reference: added a comment on the existing https://github.com/sol/interpolate/issues/11
