### ISSUE TITLE
Committed choice for parsing Objects

### ISSUE THREAD

**Issue by robrix** [bos/aeson#693]
Is there an idiomatic way to do committed choice when parsing an `Object`? E.g. we are parsing a structure which always has fields `a` and `b`, and may have `c`, `d`, or neither. Our naïve parser looks something like:

```haskell
parseJSON (Object v) = do
  a <- v .: "a"
  b <- v .: "b"
  C a b <$> v .: "c" <|> D a b <$> v .: "d" <|> pure (E a b)
```

Unfortunately, if parsing the values in `c` or `d` fails, we’ll silently discard the failures and fall back to the `E` case. Instead, we’d like to commit to parsing a `C` as soon as we see the `c` key, or a `D` as soon as we see the `d` key, and only parse the `E` if neither key exists.

In `trifecta` (for example), choices are committed by default, and can only be backtracked past with `try`; but there doesn’t seem to be an inverse `commit` operator in `aeson` (at least, not that I’ve found thus far). Our current approach is therefore agonizingly manual:

```haskell
parseJSON (Object v) = do
  a <- v .: "a"
  b <- v .: "b"
  c <- v .:? "c"
  case c of
    Just c  -> pure (C a b c)
    Nothing -> do
      d <- v .:? "d"
      case d of
        Just d  -> pure (D a b d)
        Nothing -> pure (E a b)
```

Is there a better way to implement this sort of choice?

cc @aymannadeem

**Comment by Lysxia** [comment]
These nested cases correspond to the definition of `(<|>)` for the `MaybeT` or `ExceptT` transformer, which thus provides a whole new channel for exceptions, allowing you to distinguish the two kinds of failure, bypassing the need for a `try` or `commit` operator in many common cases.

```haskell
parseJSON (Object v) = do
  a <- v .: "a"
  b <- v .: "b"
  fromJust <$> runMaybeT
    ( C a b <$> MaybeT (v .:? "c")
    <|> D a b <$> MaybeT (v .:? "d")
    <|> pure (E a b))
  -- 1. (<|>) for MaybeT doesn't swallow exceptions thrown in Parser
  -- 2. fromJust <$> runMaybeT (_ <|> pure _)   is safe, but you can also make up a proper variant of runMaybeT with exhaustive pattern-matching or fromMaybe
```

**Comment by bergmark** [comment]
Looks like this was answered.
