### ISSUE TITLE
Expose GToJSON

### ISSUE THREAD

**Issue by LukaHorvat** [bos/aeson#700]
Currently, only `GFromJSON` is exposed. `GToJSON` is only exposed via the two type synonyms which means that I can't write custom instances for that class. My use case is that I have a type (`data Unset = Unset`) that I want to use for some fields in a record and I want those fields to be dropped from the JSON representation of that record. If `GToJSON` was exposed, I could just duplicate the trick used for `Maybe`. 

Since `GFromJSON` is already exposed, this already has a precedent.

**Comment by phadej** [comment]
Writing custom instances of `GToJSON` seems somewhat phishy.

**Comment by LukaHorvat** [comment]
Sure, and I would discourage that in the docs, but it probably shouldn't be forbidden.

**Comment by bergmark** [comment]
Can we export it without making a breaking change (due to the type synonym)? Sounds reasonable to export it since GFromJSON is exported.

@LukaHorvat how are you using Unset, with a parameterized data type? Maybe we could add that to aeson?

**Comment by LukaHorvat** [comment]
@bergmark Yep, a parametrized data type. Maybe this could be added but it seems very specific to be honest.

Currently I'm working around this issue by defining a newtype which imitates the generic rep of the type it's wrapping but drops the Unset fields. Then I use XDerivingVia to get the JSON instances for my original types. I'm kind of happy with the solution since it's very general and I might need to reuse it for other classes, but I'd be even happier if I could drop these 50 lines of type class/family magic and just define a custom GToJSON instance.

**Comment by blinky3713** [comment]
I'm trying to do something similar, see [this comment](https://github.com/f-o-a-m/hs-abci-server/issues/19#issuecomment-515793384). If this is considered a bad idea, I would also take your advice and avoid doing it.

**Comment by Lysxia** [comment]
@LukaHorvat's trick sounds like what [generic-data-surgery](https://hackage.haskell.org/package/generic-data-surgery) does, and @blinky3713's code looks like what [higgledy](https://hackage.haskell.org/package/higgledy) does. There's certainly a cost in complexity for these abstractions in exchange for the added modularity.

**Comment by phadej** [comment]
@bergmark there is

```haskell
Data/Aeson/Types/Class.hs:type GToJSON = ToJSON.GToJSON Value
Data/Aeson/Types/ToJSON.hs:class GToJSON enc arity f where
```

IMO we should rename either, and have both exported.
