### ISSUE TITLE
Record field must be present when `Maybe a` introduced via type parameter

### ISSUE THREAD

**Issue by neoncrisis** [bos/aeson#707]
Introducing a `Maybe` via a type parameter allows the value to be `Null` but the field is required to be present in order for parsing to succeed.

```
data Example a = Example { field :: a } deriving (Show, Generic)
instance FromJSON a => FromJSON (Example a)

λ> eitherDecode "{}" :: Either String (Example (Maybe ()))
Left "Error in $: key \"field\" not present"
```

This behavior is contrary to how `Maybe` works when declared inline in the type declaration.

```
data Example2 a = Example2 { field :: Maybe a } deriving (Show, Generic)
instance FromJSON a => FromJSON (Example2 a)

λ> eitherDecode "{}" :: Either String (Example2 ())
Right (Example2 {field = Nothing})
```

This distinction is subtle and unintuitive and I couldn't find it documented anywhere.  The obvious workaround is to avoid using `Maybe` via type parameter, but hopefully this is an accidental omission rather than a limitation in the generic deriving machinery :)

**Comment by Lysxia** [comment]
Indeed, this is very subtle, and it should be documented.

Sadly I don't think there is a fix. Quoting myself from #690 (which is essentially the same issue):

> There is a fundamental limitation in the way type classes work that makes this infeasible. The implementation of the `omitNothingFields` option is quite fragile (...). Properly supporting this use case would require a significant redesign of aeson's generic machinery.
