### ISSUE TITLE
A release to allow hashable-1.3, semigroups-0.19 and primitive-0.7

### ISSUE THREAD

**Issue by phadej** [bos/aeson#713]

**Comment by bergmark** [comment]
Yes! I'm heading out over the weekend but I should be able to get it done on sunday.

**Comment by phadej** [comment]
@bergmark have a nice midsummer!

**Comment by asr** [comment]
Blocking https://github.com/agda/agda/issues/3768.

**Comment by andrewthad** [comment]
I believe that the `aeson-1.4.4.0` release resolves this issue. As a minor request, this release is not currently tagged on github. If any of the maintainers could tag this, it would be helpful for my workflow on some of the projects I work on.

**Comment by bergmark** [comment]
Thanks for the reminder, I forgot about that.
