### ISSUE TITLE
"key tag not present" error message is somewhat confusing

### ISSUE THREAD

**Issue by nineonine** [bos/aeson#719]
I saw this error message and it confused me - I started looking for an actual "tag" key in my JSON... 

After some research I realized tag is something related to Aeson internal machinery (?)

Perhaps we could improve this message?

I am willing to submit a patch, but we need a better message first ...

I wonder whether that happened to anyone else ... Maybe it is ok after all.

**Comment by Lysxia** [comment]
This error message could definitely be improved.

> After some research I realized tag is something related to Aeson internal machinery (?)

I'm a bit puzzled by this. The string `" not present"` only occurs in `explicitParseField` so, for that error to occur, a user of that library, maybe another dependency you're using, must have used that function with a `Text` argument `"key"` which is then expected to be in a JSON object. That's not an internal detail.

Is there more context about how you came across this error?

**Comment by nineonine** [comment]
That happened when I tried to write a FromJSON instance for one of my types. The JSON for this type is special, it has 1 field which is another stringified JSON. I think I used `withEmbeddedJSON` (although I am not sure the problem was here)
I guess by internal' I meant "something related to Aeson parsing routine".
Unfortunately, I still don't really understand what this error message is trying to tell me so I am unable to suggest something better or more meaningful.

**Comment by Lysxia** [comment]
Ah I have an idea where that might come from. `"tag"` is the default key used for the generic implementation of `FromJSON`. So given an ADT with multiple constructors with a derived `FromJSON`,

```
data T = Foo Int | Bar String deriving (Generic, FromJSON)
```

the corresponding JSON must look like:

```
{ "tag": "Foo", "contents": 3 }  // Foo 3
{ "tag": "Bar", "contents": "baz" }  // Bar "baz"
```

If your JSON input doesn't look like that, and in particular, if it is an object without such a `tag` field, you get the error you mentioned. Now I can imagine how this can occur accidentally, so that this error feels like it comes out of nowhere.

**Comment by nineonine** [comment]
Aha, that makes sense now!
I think we should either attempt to come up with better error or explain it somewhere in documentation.

**Comment by bergmark** [comment]
> I think we should either attempt to come up with better error message or explain it somewhere in documentation.

Either or both of those sound good to me, but I'm not sure how the error message can be improved, any ideas? Would `missing required field "tag"` instead of `key "tag" not present` help?

**Comment by nineonine** [comment]
I think it would be very helpful if this message mentioned or (hinted in any way) that something might have gone wrong with parsing ADT that has multiple constructors. something like `missing required field "tag" when trying to parse ADT with multiple constructors`. 
However, my case didn't have ADT with multiple constructor so I am still confused ...
I will probably distill a minimal reproducer (which eventually becomes a regression test) and then we can take a look together and decide what to do with it.

**Comment by nineonine** [comment]
I tried to repro but failed. I've spent a couple of hours. That is embarrassing...
Should we just update error message and call it a day? What do you think of my proposed message?

**Comment by bergmark** [comment]
I don't think we have enough information at this point to say "trying to parse an ADT" since `explicitParseField` can be used to parse from a json object to anything.

I'd lean more towards making the error messages agnostic to the haskell representation so that someone trying to interact with a haskell program won't get information about the internal details. I'd prefer something like `missing required field "tag" when trying to parse a JSON object into X".

Randomly I also found this part of the code which touches on the same issue. It seems to trigger only if you supply an incorrect tag. Maybe we should rewrite the error message from `.:` here to print all the available values? I think it would be easier to figure out what's going on if we get back `missing required field "tag", expected it to be one of: "x", "y"`

Data/Aeson/Types/FromJSON.hs:
```
parseNonAllNullarySum p@(tname :* opts :* _) =
    case sumEncoding opts of
      TaggedObject{..} ->
          withObject tname $ \obj -> do
              tag <- contextType tname $ obj .: tagKey
              fromMaybe (badTag tag <?> Key tagKey) $
                  parseFromTaggedObject (tag :* contentsFieldName :* p) obj
        where
          tagKey = pack tagFieldName
          badTag tag = failWith_ $ \cnames ->
              "expected tag field to be one of " ++ show cnames ++
              ", but found tag " ++ show tag
```

What do you think?

**Comment by nineonine** [comment]
> I'd prefer something like `missing required field "tag" when trying to parse a JSON object into X".

That definitely looks much better!

Another suggestion is reasonable as well.

**Comment by gdevanla** [comment]
@nineonine  I was able to produce this error as follows:
```
eitherDecode "{\"tag1\": \"Foo\", \"contents\": 10}" ::  Either String T
Left "Error in $: parsing Ghci2.T failed, key \"tag\" not present"
```

**Comment by gdevanla** [comment]
@bergmark What would 'x' and 'y' in your proposed error message be? Wouldn't just 'missing required field 'tag' suffice? Here 'tag' will be replaced by whatever value 'tagKey' is configured (the default being 'tag'.  

I also feel that the final parse errror should be left intact to provide more information on what the parse is doing. Therefore, the above error would be as follows:

eitherDecode "{\"tag1\": \"Foo\", \"contents\": 10}" ::  Either String T
Left "Error in $: parsing Ghci2.T failed, missing required field 'tag'. The parser returned: "key \"tag\" not present"

**Comment by bergmark** [comment]
> What would 'x' and 'y' in your proposed error message be? Wouldn't just 'missing required field 'tag' suffice? Here 'tag' will be replaced by whatever value 'tagKey' is configured (the default being 'tag'.

My idea was something like :

```haskell
data T = C1 String | C2 Int
eitherDecode @ T "{}" =>
Left "Missing required field "tag", expected it to be one of: "c1", "c2"
```

That way you know all alternatives, otherwise you will just get the first (or is it last?) tag, right?

**Comment by gdevanla** [comment]
Here the problem is absence of 'tagKey' called 'tag'. The error you are talking about is covered in the second block.

```
*Main Lib GHC.Generics Data.Aeson Data.Aeson.Types> eitherDecode "{\"tag\": \"Foo1\", \"contents\": 10}" ::  Either String T
Left "Error in $.tag: parsing Ghci21.T failed, expected tag field to be one of [\"Foo\",\"Bar\"], but found tag \"Foo1\""
```

You will see that this is already taken care by the `badTag` expression.

May be I am mis-understanding what you are saying given my limited experience with the library?

**Comment by bergmark** [comment]
Aha, nice

**Comment by Lysxia** [comment]
But you get that last error message only if there is a `"tag"` key in the first place. The real issue here is the error when there is no key, which isn't as helpful.

**Comment by gdevanla** [comment]
@Lysxia My fix addresses the problem when there is not tagKey.
