### ISSUE TITLE
Data.Aeson exports <?> but not JSONPathElement

### ISSUE THREAD

**Issue by leifmetcalf** [bos/aeson#726]
Data.Aeson exports the following function:
`(<?>) :: Parser a -> JSONPathElement -> Parser a `
The constructors for JSONPathElement are not exported by Data.Aeson, so this function cannot actually be used without also importing Data.Aeson.Internal as well.

**Comment by bergmark** [comment]
@luke-clifton fixed this in #723, i'll try to make a release this week.

**Comment by bergmark** [comment]
also from that discussion:

> As a workaround you can import it from Data.Aeson.Internal but that's not ideal.

**Comment by leifmetcalf** [comment]
Ah, didn't see that. Thank you.

**Comment by bergmark** [comment]
this was released in 1.4.5.0!
