### ISSUE TITLE
`FromJSON` and `ToJSON` don't roundtrip for `Char` and `String` 

### ISSUE THREAD

**Issue by NorfairKing** [bos/aeson#731]
See `\55810` for example.

**Comment by llelf** [comment]
It is a lone surrogate code point U+DA02 and has no meaning (= not a valid string).
So it is not representable by `Text` (and arguably should not be represented by `Char`).

**Comment by NorfairKing** [comment]
It's similar to `NaN` in doubles. 
I mostly opened this ticket so that I can refer to it as a known problem in the future.
I don't expect a fix.
