### ISSUE TITLE
Failing tests

### ISSUE THREAD

**Issue by tjilerom** [bos/aeson#740]
tests/ErrorMessages.hs:16:29: error: **Module ‘Data.Algorithm.Diff’ does not export ‘PolyDiff(..)’**

`16 | import Data.Algorithm.Diff (PolyDiff (..), getGroupedDiff)
`

**Comment by phadej** [comment]
... caused by `Diff-0.4.0` release.

**Comment by bergmark** [comment]
Which version of aeson are you using?

I think this was fixed in https://github.com/bos/aeson/pull/732 which was released in 1.4.6.0

**Comment by bergmark** [comment]
I believe this is resolved. Let me know if you can give a reproduction and we'll re-open.
