### ISSUE TITLE
Export CoerceText for usage.

### ISSUE THREAD

**Issue by Fuuzetsu** [bos/aeson#741]
Around https://github.com/bos/aeson/pull/399/commits/5ef5530700f1f44a72cbac959070d5a0ffe1ada4 a new type was added, CoerceText. This made coercing keys safer which is great. Sadly, this is not exported and it'd be useful if it was.

A motivating story below.

We have a [maplike class](https://github.com/takano-akio/maplike) that we use for working with strict/lazy [EnumMap](http://hackage.haskell.org/package/enummapset-th)s. I wanted to add an (orphan) instance for these EnumMap's. I started with a simple `EnumMap.fromList` but that obviously gave us the ugly list representation after serialisation. I looked in `aeson` source and followed the footsteps of `Data.Map` implementation. I got something like this

```hs
maplikeParseJSON
    :: forall k v m. (Maplike.Maplike k m, Typeable (m v), A.FromJSONKey k, A.FromJSON v)
    => A.Value -> A.Parser (m v)
maplikeParseJSON = case A.fromJSONKey of
    -- Neither coerceFromJSONKeyFunction nor CoerceText that we
    -- need to match on to get a Coercible witness are exposed
    -- from a public aeson module so we have to do an unsafeCoerce
    -- just like older aeson on older GHC version does. The
    -- constructor here is our witness.
    A.FromJSONKeyCoerce _ -> A.withObject typeName
        $ fmap (HM.foldrWithKey (Maplike.insert . unsafeCoerce) Maplike.empty)
        . HM.traverseWithKey (\k v -> A.parseJSON v A.<?> A.Key k)
    A.FromJSONKeyText f -> A.withObject typeName
        $ fmap (HM.foldrWithKey (Maplike.insert . f) Maplike.empty)
        . HM.traverseWithKey (\k v -> A.parseJSON v A.<?> A.Key k)
    A.FromJSONKeyTextParser f -> A.withObject typeName
        $ HM.foldrWithKey (\k v m -> Maplike.insert <$> f k A.<?> A.Key k <*> A.parseJSON v A.<?> A.Key k <*> m) (pure Maplike.empty)
    A.FromJSONKeyValue f -> A.withArray typeName
        $ fmap Maplike.fromList . sequence
        . zipWith (parseIndexedJSONPair f) [0 ..] . V.toList
    where
        typeName = show $ typeRep (Proxy :: Proxy (m v))
{-# INLINE maplikeParseJSON #-}
```

Notably, the problem is on FromJSONKeyCoerce case. We're forced to use `unsafeCoerce` even though we should be able to get `Coercible` constraint from its argument. If `CoerceText` was exported, I could simply use `coerce`.

**Comment by phadej** [comment]
The more correct way, would be to export only `coerceText :: CoerceText a -> Text -> a` and reverse, as `CoerceText` doesn't always carry `Coercible`, at least as far as current `aeson` support window is concerned. If we drop support for pre-GHC-7.8, then things can be simplified greatly.

**Comment by bergmark** [comment]
I'd be fine with dropping ghc < 7.8 if it simplies things.
