### ISSUE TITLE
how to parse json with field of optional and variant type in Haskell?

### ISSUE THREAD

**Issue by chakpongchung** [bos/aeson#748]
https://stackoverflow.com/questions/59903779/how-to-parse-json-with-field-of-optional-and-variant-type-in-haskell

I looked at the Twitter example in this repo. Is it a working example? If so, where can I find its corresponding json? Though I am not sure that twitter example cover the features needed to parse the full example(not the minimal) shown in the link above.

**Comment by piq9117** [comment]
Looks like this question was already answered? https://stackoverflow.com/a/59942481 maybe it can be closed?

**Comment by chakpongchung** [comment]
@piq9117 yes, I am happy with the solution in that post
