### ISSUE TITLE
Cannot build attoparsec-iso8601 on master

### ISSUE THREAD

**Issue by RyanGlScott** [bos/aeson#761]
When attempting to build the `attoparsec-iso8601` library on commit 6bd27358bf0e990fdab339158f925452e8900c3d, I get the following build error:

```
$ /opt/cabal/3.0/bin/cabal build attoparsec-iso8601
Build profile: -w ghc-8.8.3 -O1
In order, the following will be built (use -v for more details):
 - attoparsec-iso8601-1.0.1.0 (lib) (first run)
Preprocessing library for attoparsec-iso8601-1.0.1.0..
Building library for attoparsec-iso8601-1.0.1.0..
[1 of 2] Compiling Data.Attoparsec.Time.Internal ( Data/Attoparsec/Time/Internal.hs, /home/rgscott/Documents/Hacking/Haskell/aeson/dist-newstyle/build/x86_64-linux/ghc-8.8.3/attoparsec-iso8601-1.0.1.0/build/Data/Attoparsec/Time/Internal.o )

Data/Attoparsec/Time/Internal.hs:24:1: error:
    Could not load module ‘Data.Time.Clock.Compat’
    It is a member of the hidden package ‘time-compat-1.9.3’.
    Perhaps you need to add ‘time-compat’ to the build-depends in your .cabal file.
    It is a member of the hidden package ‘time-compat-1.9.3’.
    Perhaps you need to add ‘time-compat’ to the build-depends in your .cabal file.
    It is a member of the hidden package ‘time-compat-1.9.3’.
    Perhaps you need to add ‘time-compat’ to the build-depends in your .cabal file.
    It is a member of the hidden package ‘time-compat-1.9.2.2’.
    Perhaps you need to add ‘time-compat’ to the build-depends in your .cabal file.
    It is a member of the hidden package ‘time-compat-1.9.2.2’.
    Perhaps you need to add ‘time-compat’ to the build-depends in your .cabal file.
    It is a member of the hidden package ‘time-compat-1.9.2.2’.
    Perhaps you need to add ‘time-compat’ to the build-depends in your .cabal file.
    Use -v (or `:set -v` in ghci) to see a list of the files searched for.
   |
24 | import Data.Time.Clock.Compat
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

Is there a missing dependency on `time-compat` somewhere?

**Comment by RyanGlScott** [comment]
From a cursory glance, it does appear that `attoparsec-iso8601.cabal` incorrectly omits `time-compat` from its `build-depends`:

https://github.com/bos/aeson/blob/6bd27358bf0e990fdab339158f925452e8900c3d/attoparsec-iso8601/attoparsec-iso8601.cabal#L37-L42

If so, I have no idea how `master` is currently passing CI.

**Comment by phadej** [comment]
I'd like to throw out the current CI setup, and use `haskell-ci`... then i would know the answer to above question :)

**Comment by RyanGlScott** [comment]
Ah. Looking at the current state of [`travis/script.sh`](https://github.com/bos/aeson/blob/6bd27358bf0e990fdab339158f925452e8900c3d/travis/script.sh), it seems that it invoked `cabal build` rather than, say, `cabal build all`. In other words, only `aeson` gets built, not `aeson` + `attoparsec-iso8601`.

In any case, we should be able to fix this bug independently of revamping the CI. I think it just be a simple matter of adding `time-compat` to `attoparsec-iso8601.cabal`. @phadej, do you happen to know what the appropriate version bounds would be?

**Comment by bergmark** [comment]
I'm trying to get a rudimentary build step on travis.

**Comment by phadej** [comment]
@RyanGlScott same as in `aeson`.

Note: that travis setup uses `v1-build` (those are old `cabal-install`s). For that reason there are no GHC-8.8 nor GHC-8.10 jobs. The script needs more serious editing than a single step.

**Comment by bergmark** [comment]
> that travis setup uses v1-build
We use v2-build as well

> For that reason there are no GHC-8.8 nor GHC-8.10 jobs.
We had a 8.8 job, and I just added one for 8.10

That said, switching to haskell-ci would be welcome.
