### ISSUE TITLE
encode to leave out Maybe values that are Nothing

### ISSUE THREAD

**Issue by alanz** [bos/aeson#77]
I have come up with a way to not encode Maybe values that are empty, as shown in https://gist.github.com/2465584.

Is there an existing simple way to do this?

If not, should this become a feature in aeson?

```
  let reply1 = Coord 123.4 20 (Just "foo")
  BL.putStrLn (encode reply1)
  let reply = Coord 123.4 20 Nothing
  BL.putStrLn (encode reply)
```

results in

```
{"c":"foo","y":20.0,"x":123.4}
{"y":20.0,"x":123.4}
```

**Comment by Infinisil** [comment]
> (.=?) :: ToJSON a => Text -> a -> Pair
> 
> which only emits JSON if the Maybe value it is given is not Nothing.

The same has been proposed in https://github.com/haskell/aeson/issues/87

I'd still like to have such an operator. Doesn't even have to be an operator though, could also just be a function. Currently if you want to make a field optional you need to mess around with optional list elements, which is really messy, e.g.

```haskell
object (
  [ "required" .= required ]
  ++ maybe [] (\value -> ["optional" .= value]) optional
```
