### ISSUE TITLE
Invert dependency with `these`

### ISSUE THREAD

**Issue by phadej** [bos/aeson#776]
My comment on https://github.com/bos/aeson/issues/432#issuecomment-611588816 probably got unnoticed.

Making an issue out of it

The discussion about aeson These instances arose again.

What's your opinion nowadays, @bergmark. If I strip these to bare minimum, probably depending only assoc and hashable (+ GHC boot libs), would it be possible that ToJSON (These a b) etc to be moved to aeson?

Over past years my opinion become that These is a quite core type, and spreading it around would be easier if the these package become as small as possible, but I don't want make these-aeson just for few instances - I don't think it would make anything better, only increase the maintenance load.

**Comment by bergmark** [comment]
Ah, sorry!

I haven't thought about it much tbh, so if you think it's a good idea let's go for it!

**Comment by phadej** [comment]
@bergmark good. Let's do this. I'll prepare `these` candidate (and `quickcheck-instances`) release and then we can proceed.

Adding the dependency + instance would be a minor version.

**Comment by phadej** [comment]
@bergmark Thanks! Let us now see what follows.
