### ISSUE TITLE
Encode to strict ByteString

### ISSUE THREAD

**Issue by poscat0x04** [bos/aeson#780]
Is it possible to encode directly into a strict `ByteString`? I would like to avoid the overhead of converting between lazy `ByteString`s and strict `ByteString`s

**Comment by bergmark** [comment]
As far as I know, it's not possible. I'm not sure if what the implications of supporting that would be.
Sorry that this probably isn't very helpful!

**Comment by phadej** [comment]
Serializing to strict bytestring is difficult. We have (somehow) to know the size of final buffer (at least to some precision) to avoid overhead. Using bytestring `Builder` (which creates lazy bytestring chunks on need) saves us a lot of head-ache.

I.e. either we traverse twice:: first to get the buffer size and then another to write to it. Or we use builder, (and possibly second pass to make contiguous strict bytestring).

Note: if we would allocate *some* buffer, and extend it on need, that would be worse than LBS approach, as we'd copy the prefix many times. With LBS we don't.

**Comment by bergmark** [comment]
Thanks Oleg,

So this is unfortunately not something I think we will be able to support, sorry about that!
