### ISSUE TITLE
Add instances for types in strict and data-fix

### ISSUE THREAD

**Issue by phadej** [bos/aeson#794]
`strict` and `data-fix` are small packages providing strict variants of `(a,b)`, `Either`, `Maybe`, `These` and the fixed-point type `Fix` respectively.

I plan to add instances for both package to `quickcheck-instances` https://github.com/phadej/qc-instances/pull/54 https://github.com/phadej/qc-instances/pull/55.

It would be great if `aeson` instances could be migrated from `strict-base-type` package to `aeson` (as I migrate off `QuickCheck` instances). In some future I expect `strict` and `data-fix` eventually migrated to `base`. Both packages are quite small, and don't add any transitive dependencies. I also don't expect them to change often, i.e. trash people caches.

And yes, I want to promote both `strict` and `data-fix`. `data-fix` is already used by e.g. `dhall` and `hnix`, and soon `recursion-schemes`. I'd like it to become the package providing `data Fix`. `strict` has `Agda` and `stylish-haskell` as its users already (and plenty others https://packdeps.haskellers.com/reverse/strict). I especially have used `strict` types aeson instances.

I'll make a PR, if this proposal is accepted.

**Comment by sjakobi** [comment]
I haven't used `strict` before, so I have some questions:

* Where is that strict `These` variant?
* The package looks unmaintained and seems to lack some common instances. Are you planning to take it over?
* Its `Maybe` and `Either` types seem to be easy to confuse with the `base` types of the same names. Isn't this a problem in practice?

**Comment by phadej** [comment]
Package is very well maintained: https://github.com/haskell-strict/strict, we are preparing a release, and this is one question I want to resolve (so I know what to do with `strict-base-types`).

> Its Maybe and Either types seem to be easy to confuse with the base types of the same names. Isn't this a problem in practice?

In my experience the same as confusing strict and lazy texts or bytestrings. I.e. No.
- Which is good point, let me add a note that `Data.Strict(.*)` modules are designed to be imported qualified.

**Comment by phadej** [comment]
We have now happy with the state of `strict` package, and ready for it to be released. (There was one change, which doesn't affect #795). We now depend on this change to approved or rejected.

ping @bergmark
