### ISSUE TITLE
how to generate literal javascript expression

### ISSUE THREAD

**Issue by eflister** [bos/aeson#807]
i don't know anything about javascript, JSON, aeson, or quasiquoting, so go easy on me.  :)

i'm using [this function](https://hackage.haskell.org/package/hvega-0.10.0.0/docs/Graphics-Vega-VegaLite.html#v:toHtmlFileWith) and need to pass it something that will make a [`Value`](https://hackage.haskell.org/package/aeson-1.5.1.0/docs/Data-Aeson-Types.html#t:Value) `{ logLevel : vega.Debug }`.  this is supposed to refer to an [enum](https://github.com/vega/vega/blob/master/packages/vega-util/src/logger.js#L6) in the javascript package that the binding doesn't export.

afaict i'm supposed to use `Data.Aeson.QQ.Simple` for this, but everything i try that compiles puts quotes around `"vega.Debug"`, which i can't have.
```haskell
[aesonQQ| { logLevel : "vega.Debug" } |]
```

any guidance?  thank you!

**Comment by eflister** [comment]
got a great answer [here](https://stackoverflow.com/questions/64175005/how-do-i-use-aeson-to-generate-a-literal-unquoted-javascript-expression) -- looks like `Aeson` won't do this.  i can close the issue, or does this kind of thing arise often enough to consider some kind of `Aeson` solution?

**Comment by bergmark** [comment]
Sorry for the late reply, but good to see that you got an answer!. Aeson is only meant to handle JSON, stripping quotes is outside of the scope of this package. We have requests for similar exceptions frequently but it would not be manageable to handle all of them.

**Comment by eflister** [comment]
ok, np. do you mind saying what you think of the `toEncoding` solution?
> you could make a `ToJSON` instance for your type that implements `toEncoding` but not `toJSON`, and have the encoded value be a JavaScript expression (i.e. invalid JSON).
