### ISSUE TITLE
How to deal with fields that are not valid Haskell field names using DeriveGeneric ?

### ISSUE THREAD

**Issue by arademaker** [bos/aeson#814]
In the JSON I am processing, I have fields like `i-id`. But does are exceptions. How to deal with them but keep using the DeriveGeneric for automatic generate the instance from data types?

**Comment by phadej** [comment]
https://hackage.haskell.org/package/aeson-1.5.4.1/docs/Data-Aeson.html#v:fieldLabelModifier
