### ISSUE TITLE
aeson-0.11 needs time >= 1.1.4 revision

### ISSUE THREAD

**Issue by Bodigrim** [bos/aeson#884]
```
$ cabal unpack aeson-0.11.0.0 
$ cd aeson-0.11.0.0 
$ cabal build --constraint 'time < 1.1.4' -w ghc-7.10

Data/Aeson/Parser/Time.hs:33:33:
    Module ‘Data.Time.Calendar’ does not export ‘fromGregorianValid’ 
```

`fromGregorianValid` was introduced in [`time-1.1.4`](https://hackage.haskell.org/package/time-1.1.4/docs/Data-Time-Calendar.html).

I did not check other versions of `aeson`, they might need such revision as well.

**Comment by phadej** [comment]
It turns out the lower bound was needed from `aeson-0.10.0.0` to `aeson-1.4.1.0` (with older GHCs there were install plans). Good catch.

There are failures with older then `aeson-0.10` when using older `time` too:

```
Data/Aeson/Generic.hs:118:10:
    Could not deduce (Typeable UTCTime) arising from a use of ‘extQ’
```

but these are different. I'll check then soon.
